package shared

  /** Generated: concept/contrast term -> most relevant compendium heading
    * (week-constrained fuzzy match, chapter fallback). Edit to correct. */
  lazy val conceptHeading: Map[String, String] = Map(
    "funktion" -> "Funktion, argument, parameter",
    "while-sats" -> "Uttryck eller sats?",
    "for-sats" -> "Uttryck eller sats?",
    "stränginterpolator" -> "Introduktion",
    "tilldelning" -> "Förkortade tilldelningssatser",
    "kompilering" -> "Introduktion",
    "grundtyper" -> "Grundtyper i Scala",
    "booleskt värde" -> "Variabler som ändrar värden kan vara knepiga",
    "exekvering i sekvens" -> "Introduktion",
    "abstraktion" -> "Virtuell maskin (VM) == abstrakt hårdvara",
    "for-uttryck" -> "Bygg ny samling från befintlig med for-yield-uttryck",
    "indexering" -> "Program, kontrollstrukturer, maskinkod",
    "kontrollstruktur" -> "Vad är en kontrollstruktur?",
    "huvudprogram" -> "Program, kontrollstrukturer, maskinkod",
    "anonym funktion" -> "Anonyma funktioner",
    "predikat" -> "Predikat, med och utan namn",
    "äkta funktion" -> "Äkta funktioner",
    "aktiveringspost" -> "Anropsstacken och aktiveringsposter",
    "anropsstacken" -> "Anropsstacken och objektheapen",
    "defaultargument" -> "Funktioner med defaultargument",
    "returtyp" -> "Funktioner och abstraktion",
    "namngivna argument" -> "Funktioner med namngivna argument",
    "lokal funktion" -> "Lokala funktioner",
    "funktion som äkta värde" -> "Funktioner är äkta värden i Scala",
    "samlingsmetoden map" -> "Applicera funktioner på element i samlingar med map",
    "singelobjekt" -> "Singelobjekt är lata",
    "paket" -> "Paket i REPL",
    "privat medlem" -> "Idiom: Privata variabler med understreck vid krock",
    "namnrymd" -> "Namnrymd och skuggning",
    "metoden apply" -> "Ett smidigt sätt att skapa 2-tupler med metoden ->",
    "tupel" -> "Vad är en tupel?",
    "import" -> "Namnbyte vid import",
    "punktnotation" -> "Punktnotation och operatornotation",
    "extensionsmetod" -> "Kollektiva extensionsmetoder",
    "classpath" -> "Vad är classpath?",
    "klass" -> "Case-klasser",
    "attribut" -> "Förhindra felaktiga attributvärden med setters",
    "fabriksmetod" -> "Indirekt instansiering med fabriksmetoder",
    "instansiering" -> "Hur förhindra direkt instansiering?",
    "tillstånd" -> "Förändring av objektets tillstånd",
    "klassparameter" -> "Vad är en klass?",
    "kompanjonsobjekt" -> "Kompanjonsobjekt med indirekt instansiering",
    "nyckelordet this" -> "Referensen this",
    "strängrepresentation" -> "Klasser och datamodellering",
    "mönstermatchning" -> "Mönster och felhantering",
    "undantag" -> "Undvik undantag om det går",
    "konstruktormönster" -> "Konstruktormönster med case-klasser",
    "Option" -> "Några smidiga metoder på Option",
    "Try" -> "Primitiva try-catch-uttryck",
    "förseglad typ" -> "Mönstermatchning och förseglade typer",
    "pseudokod" -> "Pseudo-kod för SEQ-INSERT-COPY",
    "sekvensalgoritm" -> "Vad är en sekvens?",
    "filtrering" -> "Använda samlingsmetoden filter för filtrering",
    "transformering" -> "Sekvenser och enumerationer",
    "registrering" -> "Registrering",
    "att ändra på plats" -> "Skapa ny sekvenssamling eller ändra på plats?",
    "likhet mellan strängar" -> "Jämföra strängar: likhet",
    "sorterad sekvens av strängar" -> "Exempel: En sträng är en sekvens av tecken",
    "enumeration" -> "Enum och mönster-matchning",
    "linjärsökning" -> "Linjärsökning: hitta index för elementet x",
    "insättningssortering" -> "Insättningssortering på plats -- pseudo-kod",
    "repeterade parametrar" -> "Repeterade parametrar blir sekvens",
    "matris" -> "Vad är en matris?",
    "nästlad struktur" -> "Iterera över nästlad struktur",
    "typparameter" -> "Vad är en typparameter?",
    "generisk funktion" -> "Exempel: Generisk funktion",
    "mängd" -> "Vad är en mängd?",
    "nyckel-värde-tabell" -> "Vad är en nyckel-värde-tabell?",
    "innehållstest" -> "Mängder och tabeller, versionshantering",
    "serialisering" -> "Serialisering och deserialisering",
    "persistens" -> "Mängder och tabeller, versionshantering",
    "arv" -> "Vad är arv?",
    "subtypspolymorfism" -> "Subtypspolymorfism och dynamisk bindning",
    "bastyp" -> "Behovet av gemensam bastyp",
    "final medlem" -> "En final medlem kan ej överskuggas",
    "skyddad medlem (protected)" -> "Arv och komposition",
    "överskuggning (override)" -> "Exempel: Överskuggning och override",
    "dynamisk bindning" -> "Subtypspolymorfism och dynamisk bindning",
    "kod-duplicering" -> "Arv och komposition",
    "anonym klass" -> "Anonym klass",
    "while-sats | for-sats" -> "Uttryck eller sats?",
    "typ | värde" -> "Variabler som ändrar värden kan vara knepiga",
    "if-uttryck | if-sats" -> "Uttryck eller sats?",
    "def | val" -> "Introduktion",
    "var | val" -> "Introduktion",
    "kompileringsfel | körtidsfel" -> "Introduktion",
    "Char | String" -> "Introduktion",
    "källkod | maskinkod" -> "Virtuell maskin (VM) == abstrakt hårdvara",
    "pseudokod | exekverbar implementation" -> "Program, kontrollstrukturer, maskinkod",
    "parameter | argument" -> "Parameter och argument",
    "returtyp | parametertyp" -> "Parameter och argument",
    "for-uttryck | for-sats" -> "Bygg ny samling från befintlig med for-yield-uttryck",
    "Vector | Array" -> "Program, kontrollstrukturer, maskinkod",
    "överlagring | defaultargument" -> "Funktioner med defaultargument",
    "namngivna argument | defaultargument" -> "Funktioner med namngivna argument",
    "map | foreach" -> "Applicera funktioner på element i samlingar med map",
    "värdeanrop | namnanrop" -> "Värdeanrop och namnanrop",
    "val | lazy val" -> "Vad är skillnaden mellan val, var, def, lazy val?",
    "def | lazy val" -> "Vad är skillnaden mellan val, var, def, lazy val?",
    "funktion | metod" -> "Klasser och datamodellering",
    "klass | case-klass" -> "Case-klasser",
    "singelobjekt | klass" -> "Singelobjekt jämfört med klass",
    "getter | setter" -> "Getters och setters",
    "referenslikhet | innehållslikhet" -> "Referenslikhet eller innehållslikhet?",
    "Try | try-catch" -> "Primitiva try-catch-uttryck",
    "förseglad (sealed) typhierarki | ej förseglad typhierarki" -> "Mönster och felhantering",
    "ArrayBuffer | Array" -> "Några konstigheter med Array",
    "förändringsbar samling | oföränderlig samling" -> "Oföränderlig eller förändringsbar?",
    "skapa ny sekvens | ändra på plats" -> "Skapa ny sekvenssamling eller ändra på plats?",
    "uppräknade värden med heltal | uppräknade värden med enum" -> "Sekvenser och enumerationer",
    "List | ListBuffer" -> "Sekvenser och enumerationer",
    "matris | vektor" -> "Vad är en matris?",
    "generisk datastruktur | generisk funktion" -> "Exempel: Generisk funktion",
    "mängd | sekvens" -> "Vad är en mängd?",
    "mängd | nyckel-värde-tabell" -> "Vad är en nyckel-värde-tabell?",
    "nyckel-värde-tabell | sekvens" -> "Vad är en nyckel-värde-tabell?",
    "subtyp | supertyp" -> "Hur förhindra subtypning?",
    "klass | trait" -> "Trait eller abstrakt klass?",
    "arv | komposition" -> "Arv och komposition",
    "abstrakt medlem | konkret medlem" -> "Abstrakta och konkreta medlemmar",
    "statisk typ | dynamisk typ" -> "Statisk och dynamisk typ"
  )
