package shared

lazy val termsEn = Seq[(Week, Concepts | Contrasts | Code)](
  Week(1) -> Concepts(
    "function",
    "while statement",
    "for statement",
    "string interpolator",
    "assignment",
    "compilation",
    "basic types",
    "boolean value",
    "sequential execution",
    "abstraction"
  ),
  Week(1) -> Contrasts(
    "while statement" -> "for statement",
    "type" -> "value",
    "if expression" -> "if statement",
    "`def`" -> "`val`",
    "`var`" -> "`val`",
    "compile-time error" -> "run-time error",
    "`Char`" -> "`String`",
    "source code" -> "machine code"
  ),
  Week(1) -> Code(
    "a function `double` that takes an integer and returns the number multiplied by two" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion,%20argument,%20parameter",
    "a function `square` that takes an integer n and returns n to the power of two" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion,%20argument,%20parameter",
    "an expression that computes the remainder when 41 is divided by 2 using the operator %" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "an expression that computes the integer part of 41 divided by 2" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "a boolean expression that is true exactly when the integer n is divisible by 3" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "a boolean expression that is true exactly when age is between 13 and 19" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "an if expression that returns the string \"pass\" if the score is at least 50, otherwise \"fail\"" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20med%20if-uttryck",
    "an expression that concatenates the strings \"foot\" and \"ball\" into a single string" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering",
    "an expression that repeats the string \"ha\" 10 times using the operator *" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering",
    "an expression that computes the area of a circle given the radius r (the area of a circle is π·r², where π is available as `math.Pi`)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Definiera%20namn%20p%C3%A5%20uttryck",
    "a boolean expression that is true if x is greater than zero or x is less than -42" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20med%20if-uttryck",
    "a loop that prints the first 42 integers" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kontrollstrukturer:%20alternativ%20och%20repetition",
    "an expression that computes the sum of the numbers 7 and 5" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "an expression that computes the product of the numbers 9 and 6" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "an expression that computes the remainder when 100 is divided by 7" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "given an integer n, an expression that gives n increased by one" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "given an integer n, an expression that gives n to the power of two" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "given an integer n, an expression that gives the last digit of n" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "given two integers a and b, an expression that gives their average as a `Double`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Flyttalsaritmetik",
    "given a radius r, an expression that gives the circle's circumference (the circumference of a circle is 2·π·r)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Flyttalsaritmetik",
    "given width b and height h, an expression that gives the rectangle's area" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Flyttalsaritmetik",
    "given degrees Celsius c, an expression that gives the corresponding temperature in Fahrenheit (Fahrenheit = Celsius · 9/5 + 32)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Flyttalsaritmetik",
    "given an integer n, a boolean expression that is true if n is even" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "given an age in years, a boolean expression that is true if the person is of legal age (of legal age = at least 18 years)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "given a temperature, a boolean expression that is true if it is below zero" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "given two integers a and b, a boolean expression that is true if they are equal" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "given an integer n, a boolean expression that is true if n is divisible by both 2 and 3" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "given a first name and a last name, an expression that joins them into a full name with a space in between" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering",
    "given a name, an expression that uses a string interpolator to build the greeting \"Hello <name>!\"" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering",
    "given a string s, an expression that gives the string s repeated three times" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering"
  ),
  Week(2) -> Concepts(
    "for expression",
    "indexing",
    "control structure",
    "main program"
  ),
  Week(2) -> Contrasts(
    "pseudocode" -> "executable implementation",
    "parameter" -> "argument",
    "return type" -> "parameter type",
    "for expression" -> "for statement",
    "`Vector`" -> "`Array`"
  ),
  Week(2) -> Code(
    "a program that prints the number of negative integers in args" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Algoritmexempel:%20MIN",
    "a function that with a while loop returns the product of all integers in an `Array[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "an expression that with for-yield builds a new `Vector` where each number in xs has been increased by 10" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Bygg%20ny%20samling%20fr%C3%A5n%20befintlig%20med%20for-yield-uttryck",
    "a function that with a for-yield expression returns the square of each number in a `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Bygg%20ny%20samling%20fr%C3%A5n%20befintlig%20med%20for-yield-uttryck",
    "a program that with a for-do statement prints each element in args on its own line together with its position number" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20med%20Range",
    "a function that with a while loop counts the number of elements in an `Array[Int]` that are evenly divisible by 3" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "an expression that with `Range` and for-yield creates a `Vector` with the first ten odd numbers" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Samlingen%20Range%20h%C3%A5ller%20reda%20p%C3%A5%20intervall",
    "a function that with for-yield returns a new `Vector[String]` where each string in a `Vector` has had an exclamation mark added at the end" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Bygg%20ny%20samling%20fr%C3%A5n%20befintlig%20med%20for-yield-uttryck",
    "a program that with @main receives an integer n and the rest as strings and prints the last n strings" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Typs%C3%A4kra%20argument%20till%20ett%20program%20med%20@main",
    "a function that with a while loop returns the average of the numbers in an `Array[Int]` or zero if the array is empty" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Algoritmexempel:%20MIN",
    "an expression that with `Range` and sum computes the sum of all even numbers from 0 up to and including 100" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20med%20Range%20skapad%20med%20to",
    "a function that with a for-do statement and a var variable counts how many times the number zero occurs in a `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "a program that swaps the second and the second-to-last element in args and prints the result with spaces in between" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20Array?",
    "a function that with indexing and a while loop returns the index of the first negative number in an `Array[Int]` or minus one if none exists" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Algoritmexempel:%20MIN",
    "a function that gives the smallest integer in an integer sequence,\nwithout using the built-in min" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "a function that gives the largest integer in an integer sequence,\nwithout using the built-in max" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "two mutable variables that are first initialized\nwith two different integers and then swap values with each other" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20algoritm?",
    "a function that sums all integers in a sequence,\nwithout using the built-in sum" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20elementen%20i%20en%20vektor",
    "a loop that with a for statement prints the square of the numbers 1 to 10" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20med%20Range",
    "a loop that with a while statement prints the numbers from 10 down to 1" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "a loop that rolls 100 dice and counts the number of ones" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats"
  ),
  Week(3) -> Concepts(
    "anonymous function",
    "predicate",
    "pure function",
    "activation record",
    "the call stack",
    "default argument",
    "return type",
    "named arguments",
    "local function",
    "function as a first-class value",
    "the collection method `map`"
  ),
  Week(3) -> Contrasts(
    "overloading" -> "default argument",
    "named arguments" -> "default argument",
    "`map`" -> "`foreach`",
    "call-by-value" -> "call-by-name"
  ),
  Week(3) -> Code(
    "a predicate that determines whether a string is a palindrome, that is, reads the same forwards and backwards" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "a function that returns the product of two integers" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "a function that computes the area of a rectangle from width and height and returns a `Double`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "a function that greets a person by returning the string \"Hello \" followed by a name, with default argument \"world\"" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktioner%20med%20defaultargument",
    "a function that raises an integer to an exponent with default argument 2" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktioner%20med%20defaultargument",
    "a function that returns a formatted address from the parameters street, number and city and calls it with named arguments in any order" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktioner%20med%20namngivna%20argument",
    "an anonymous function that doubles an integer and applies it to all elements in `Vector(1, 2, 3)` with `map`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Applicera%20anonyma%20funktioner%20p%C3%A5%20element%20i%20samlingar",
    "an anonymous function that adds an exclamation mark after a string and applies it to `Vector(\"hi\", \"ho\")` with `map`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Applicera%20anonyma%20funktioner%20p%C3%A5%20element%20i%20samlingar",
    "an anonymous function with placeholder syntax that triples an integer and applies it to `Vector(1, 2, 3)` with `map`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Platsh%C3%A5llarsyntax%20f%C3%B6r%20anonyma%20funktioner",
    "a predicate that determines whether an integer is even" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "a predicate that determines whether a string is empty and filters `Vector(\"a\", \"\", \"b\")` with `filter`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "a predicate that determines whether an integer is positive and splits `Vector(-2, 3, -1, 5)` with `partition`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "a higher-order function that applies a `given` function of type `Int` => `Int` three times to an integer" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktionsv%C3%A4rden%20kan%20vara%20argument",
    "a function with two parameter lists that adds two integers and calls it with both arguments" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Multipla%20parameterlistor",
    "a recursive function that computes the factorial of an integer (the factorial n! = 1·2·…·n, and 0! = 1)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Rekursiva%20funktioner",
    "an anonymous function `Int` => `Int` that gives the square and is applied to all elements in an integer sequence" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anonyma%20funktioner",
    "a definition of an impure function that returns random even integers between n and m" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel%20p%C3%A5%20o%C3%A4kta%20funktioner:%20slumptal",
    "a function `roll` that gives a random integer between 1 and 6" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel%20p%C3%A5%20o%C3%A4kta%20funktioner:%20slumptal",
    "a function `circumference` that takes a radius of type `Double` and gives the circle's circumference (the circumference of a circle is 2·π·r)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "a function `isAdult` that takes an age of type `Int` and returns `true` if the age is at least 18, otherwise `false`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "a function `average` that takes two decimal numbers and gives their mean" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "a function `isFreezing` that takes a temperature and returns `true` if it is below zero" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "a function `rectangleArea` that takes width and height and gives the rectangle's area" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "a function `celsiusToFahrenheit` that converts degrees Celsius to Fahrenheit (Fahrenheit = Celsius · 9/5 + 32)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "a function `isEven(n: Int)` that is true if n is an even number" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn"
  ),
  Week(4) -> Concepts(
    "singleton object",
    "package",
    "private member",
    "namespace",
    "the `apply` method",
    "tuple",
    "`import`",
    "dot notation",
    "extension method",
    "classpath"
  ),
  Week(4) -> Contrasts(
    "`val`" -> "`lazy` `val`",
    "`def`" -> "`lazy` `val`"
  ),
  Week(4) -> Code(
    "an extension method that adds the methods inc and dec on integers so that the number is increased respectively decreased by one" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%A4gg%20till%20metoder%20i%20efterhand%20med%20extension",
    "a type alias Pt for the tuple type (`Int`, `Int`) and a function that takes two points of type Pt and returns their so-called Manhattan distance, defined as the sum of the absolute values of the differences between the respective coordinates, that is in mathematical notation: |x1 - x2| + |y1 - y2| " -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Typalias%20f%C3%B6r%20att%20abstrahera%20typnamn",
    "a singleton object called `myBankAccount` with an immutable account number, a mutable balance and a predicate `isInDebt` that is true when the balance is negative" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20singelobjektet%20med%20f%C3%B6r%C3%A4ndringsbart%20tillst%C3%A5nd",
    "a singleton object called `Counter` with a private variable _count starting at zero, a getter count and a method `increment` that increases the counter by one" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Inkapsling:%20att%20d%C3%B6lja%20interna%20delar",
    "a singleton object called `Thermostat` with a private variable _temp, a getter temp and a method `raise` that increases the temperature by a given number of degrees" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Inkapsling:%20att%20d%C3%B6lja%20interna%20delar",
    "a function called `length` that takes a 2-tuple (`Double`, `Double`) as parameter and gives the distance to the origin with `math.hypot`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "a function called `polar` that takes a 2-tuple (`Double`, `Double`) and returns a 2-tuple with length and angle computed with `math.hypot` and `math.atan2`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "a function called `midpoint` that takes two 2-tuples (`Double`, `Double`) and returns a 2-tuple with the average of the x-coordinates and the average of the y-coordinates" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "a function called `splitEvenOdd` that takes an integer sequence and returns a 2-tuple with the even numbers in the first element and the odd ones in the second" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "a type alias called `Pt` for the type (`Int`, `Int`) and a function `distToOrigo` that takes a Pt and gives the distance to the origin with `math.hypot`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Typalias%20f%C3%B6r%20att%20abstrahera%20typnamn",
    "an extension method called `square` on the type `Int` that gives the number multiplied by itself" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%A4gg%20till%20metoder%20i%20efterhand%20med%20extension",
    "collective extension methods on the type `Double` with half that gives the number divided by two and double that gives the number times two, gathered under one and the same `extension`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kollektiva%20extensionsmetoder",
    "a singleton object called `Colors` that, with renaming on `import`, makes `java.awt.Color` available as JColor" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Namnbyte%20vid%20import",
    "a lazy variable that with `lazy` `val` delays the initialization of a large vector until it is referenced for the first time" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Lata%20variabler%20med%20f%C3%B6rdr%C3%B6jd%20initialisering",
    "a pair that with the method -> associates the string \"Age\" with the number 42, and a vector with three such pairs" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Ett%20smidigt%20s%C3%A4tt%20att%20skapa%202-tupler%20med%20metoden%20->",
    "a singleton object `Highscore` with a private variable for the highest score,\na getter, a method `isHighscore(p: Int)` and a method `update(p: Int)` that changes the state" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20singelobjektet%20med%20f%C3%B6r%C3%A4ndringsbart%20tillst%C3%A5nd",
    "a function that takes a point as a 2-tuple (`Double`, `Double`)\nand returns a new 2-tuple changed in any way, and show how to access the parts with dot notation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "an extension method on `String` that gives the string reversed and in uppercase,\nand call it both with dot notation and as an ordinary function" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kollektiva%20extensionsmetoder"
  ),
  Week(5) -> Concepts(
    "class",
    "attribute",
    "factory method",
    "instantiation",
    "state",
    "class parameter",
    "companion object",
    "the keyword this",
    "string representation"
  ),
  Week(5) -> Contrasts(
    "function" -> "method",
    "class" -> "case class",
    "singleton object" -> "class",
    "getter" -> "setter",
    "reference equality" -> "content equality"
  ),
  Week(5) -> Code(
    "a case class that models a book with title, author and number of pages, as well as a method that returns a new copy with one page added" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "a case class that models a temperature in Celsius with a derived attribute that gives the corresponding value in Fahrenheit (Fahrenheit = Celsius · 9/5 + 32)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "a case class that models a rectangular room with width and height and a derived attribute that gives the area" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "a case class that models a bank account with owner and balance, as well as a method that returns a new copy with a deposited amount added to the balance" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "a case class that models a vector in two dimensions with dx and dy and a derived attribute that gives the length with `math.hypot`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Klassen%20Complex",
    "a class that has the class parameters first name, last name and city and its own `toString` that gives a nice string representation with string interpolation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Skapa%20egen%20najs%20toString",
    "a class that has the class parameters title and length in minutes for a movie and its own `toString` that shows the state with string interpolation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Skapa%20egen%20najs%20toString",
    "a class that has a class parameter name and a mutable class parameter score with default argument zero as well as its own `toString`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%B6sning:%20klassen%20Person",
    "a companion object that contains a factory method `apply` which creates an instance of an immutable class with a private constructor" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kompanjonsobjekt%20med%20indirekt%20instansiering",
    "a companion object that contains an immutable shared `val` that specifies a default color common to all instances of the class" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Attribut%20i%20kompanjonsobjekt%20anv%C3%A4ndas%20f%C3%B6r%20s%C3%A5dant%20som%20%C3%A4r%20gemensamt%20f%C3%B6r%20alla%20instanser",
    "a class that has a private attribute for balance and a setter that with `require` prevents negative values" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=F%C3%B6rhindra%20felaktiga%20attributv%C3%A4rden%20med%20setters",
    "a class that has a private attribute for a percentage value and a getter as well as a setter that only allows values between zero and one hundred" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Getters%20och%20setters%20i%20Scala",
    "a case class that models a date with year, month and day and a method that returns a new copy with the day increased by one" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "a case class that models a circle with radius and a derived attribute that gives the area with `math.Pi` (the area is π·r²)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Datamodellering",
    "a class that models a counter with a private attribute and methods to increase by one and read the current value" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Getters%20och%20setters%20i%20Scala",
    "a case class that models a player with name and lives and a method that returns a new copy with one life removed" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Case-klasser%20%C3%A4r%20som%20vanliga%20klasser%20med%20extra%20godis",
    "a class `Person` with class parameters for first name, last name and age\nand its own `toString` that gives a readable string representation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Skapa%20egen%20najs%20toString",
    "an immutable case class `Point` and explain the difference between == and eq,\nand use `copy` to create a partially changed copy" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "a class with a private variable for age that is protected by a getter\nand a setter that prevents negative values" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=F%C3%B6rhindra%20felaktiga%20attributv%C3%A4rden%20med%20setters"
  ),
  Week(6) -> Concepts(
    "pattern matching",
    "exception",
    "constructor pattern",
    "`Option`",
    "`Try`",
    "sealed type"
  ),
  Week(6) -> Contrasts(
    "`Try`" -> "try-catch",
    "sealed (`sealed`) type hierarchy" -> "non-sealed type hierarchy"
  ),
  Week(6) -> Code(
    "a function that with a match expression takes a `Vector` of strings and returns empty if it is empty, the single element reversed if it has one element, otherwise the first and last element joined together" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Plocka%20is%C3%A4r%20samlingar%20med%20djupa%20m%C3%B6nster",
    "a function that with a match expression takes a tuple of two integers and returns equal if the numbers are equal, increasing if the first is less than the second, otherwise decreasing" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20p%C3%A5%20tupler",
    "a match expression that takes a string day and returns weekend if the value is Saturday or Sunday, otherwise weekday, with constant patterns and a wildcard branch" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kolla%20om%20det%20passar%20med%20match-uttryck",
    "a match expression that takes an integer grade and returns fail for 0, 1, 2, pass for 3, 4 and pass with distinction for 5, with or-patterns and a wildcard branch last" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20med%20eller-m%C3%B6nster",
    "a function that with a match expression and guards returns negative if n is less than zero, zero if n is zero and positive otherwise" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20med%20gard",
    "a match expression that matches a dice roll and returns six with a guard, otherwise binds a variable pattern and returns the roll" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20med%20variabelm%C3%B6nster",
    "a function that with typed patterns takes a value of type `Any` and returns different strings depending on whether the value is an `Int`, a `String` or something else" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20med%20typade%20m%C3%B6nster",
    "a case class `Point` and a function that with a constructor pattern returns on the axis if the point lies on an axis, otherwise in the plane" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Konstruktorm%C3%B6nster%20med%20case-klasser",
    "a match expression that takes apart a tuple of name and age and with a guard returns different strings for even respectively odd age" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20p%C3%A5%20tupler",
    "a sealed base type `CompassDirection` with four case objects and a function that with a match expression returns the opposite compass direction" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=M%C3%B6nstermatchning%20och%20f%C3%B6rseglade%20typer",
    "an enumeration `TrafficLight` and a function that with a match expression returns the next light in order" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=M%C3%B6nstermatcha%20enumeration",
    "a function that with `getOrElse` returns the value in an `Option` if it exists, otherwise the string \"missing\"" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20smidiga%20metoder%20p%C3%A5%20Option",
    "a function that with a match expression on `Some` and `None` describes whether an Option value exists or is missing" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Option%20f%C3%B6r%20hantering%20av%20ev.%20saknade%20v%C3%A4rden",
    "a function that with `map` doubles the value in an `Option` if it exists, otherwise gives `None`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20smidiga%20metoder%20p%C3%A5%20Option",
    "a function that with `require` requires that the argument is not negative before it returns the square root" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Orsaka%20undantag%20indirekt%20med%20require%20och%20assert",
    "a function that with `throw` throws an exception if a withdrawal is larger than the balance, otherwise returns the new balance" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kasta%20undantag%20direkt%20med%20primitiva%20throw",
    "a try-catch expression that computes an integer division and catches an ArithmeticException by returning minus one" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Primitiva%20try-catch-uttryck",
    "a function that with a try-catch expression looks up an element at an index and catches an IndexOutOfBoundsException by returning zero" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Primitiva%20try-catch-uttryck",
    "a function that with a match expression on `Success` and `Failure` describes the result of a `Try`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hantera%20undantag%20som%20ett%20v%C3%A4rde%20med%20Try",
    "a sealed (`sealed`) type hierarchy of vegetables and a function that with\npattern matching and a guard classifies a vegetable (exhaustive matching)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=M%C3%B6nstermatchning%20och%20f%C3%B6rseglade%20typer",
    "a function that looks up a value in a key-value table and gives a\ndefault value if the key is missing, and a variant that pattern matches on `Some` and `None`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Option%20f%C3%B6r%20hantering%20av%20ev.%20saknade%20v%C3%A4rden",
    "a function that parses a string to an integer and catches any error\nwith `Try`, and a variant that uses try-catch" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hantera%20undantag%20som%20ett%20v%C3%A4rde%20med%20Try"
  ),
  Week(7) -> Concepts(
    "pseudocode",
    "sequence algorithm",
    "filtering",
    "transformation",
    "tallying",
    "modifying in place",
    "equality between strings",
    "sorted sequence of strings",
    "enumeration",
    "linear search",
    "insertion sort",
    "repeated parameters"
  ),
  Week(7) -> Contrasts(
    "`ArrayBuffer`" -> "`Array`",
    "mutable collection" -> "immutable collection",
    "create a new sequence" -> "modify in place",
    "enumerated values with integers" -> "enumerated values with `enum`",
    "`List`" -> "`ListBuffer`"
  ),
  Week(7) -> Code(
    "an `enum` `CompassDirection` with the cases North, East, South and West and a function that with pattern matching gives the opposite compass direction" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enum%20och%20m%C3%B6nster-matchning",
    "an `enum` `Coin` where each case has a denomination value in öre as parameter and a method that gives the value in kronor as `Double` (1 krona = 100 öre)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enumerationer%20kan%20ha%20parametrar%20och%20medlemmar",
    "a function that with the method `filter` gives a new vector with only the positive integers from a `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anv%C3%A4nda%20samlingsmetoden%20filter%20f%C3%B6r%20filtrering",
    "a function that with the method `filter` gives a new vector with only the strings that are longer than three characters from a `Vector[String]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anv%C3%A4nda%20samlingsmetoden%20filter%20f%C3%B6r%20filtrering",
    "a function that with the method `map` gives a new vector where each integer in a `Vector[Int]` has been doubled" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Implementation%20av%20sekvensproblem%20med%20map,%20filter",
    "a function that with the method `map` gives a new vector with the length of each string in a `Vector[String]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Implementation%20av%20sekvensproblem%20med%20map,%20filter",
    "a function that with the method `count` counts the number of even integers in a `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20anv%C3%A4ndbara%20samlingsmetoder%20vid%20implementation%20av%20sekvensalgoritmer",
    "a function that with the method `find` gives the first element in a `Vector[String]` that begins with the letter a" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20anv%C3%A4ndbara%20samlingsmetoder%20vid%20implementation%20av%20sekvensalgoritmer",
    "a function that with a for expression and a guard gives a new vector with only the integers in a `Vector[Int]` that are divisible by three" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anv%C3%A4nda%20for-uttryck%20f%C3%B6r%20filtrering%20med%20hj%C3%A4lp%20av%20gard",
    "a function that with a while statement counts and returns the number of negative integers in a `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "a function that with a while statement gives the sum of all integers in an `Array[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "an `enum` that enumerates the four seasons Spring, Summer, Autumn and Winter" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enumerationer%20har%20en%20ordning",
    "an `enum` called `TrafficLight` with the cases Red, Yellow and Green and a parameter stops of type `Boolean` where Red and Yellow stop but Green does not" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enumerationer%20kan%20ha%20parametrar%20och%20medlemmar",
    "an `enum` called `Planet` with a parameter mass of type `Double` and a member method that gives the mass doubled" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enumerationer%20kan%20ha%20parametrar%20och%20medlemmar",
    "a function with repeated parameters of type `Int` that gives the number of arguments that are greater than zero" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Repeterade%20parametrar%20blir%20sekvens",
    "a function with repeated parameters of type `Double` that gives the average of the arguments" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Repeterade%20parametrar%20blir%20sekvens",
    "a predicate that takes two strings and gives `true` if they begin with the same letter" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "a function that with the method `sortBy` gives a new vector with the strings in a `Vector[String]` sorted by their length" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20anv%C3%A4ndbara%20samlingsmetoder%20vid%20implementation%20av%20sekvensalgoritmer",
    "a function that with the method `sortWith` gives a new vector with the integers in a `Vector[Int]` sorted from largest to smallest" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Sortera%20till%20ny%20samling%20med%20godtyckligt%20ordningspredikat",
    "a function that linearly searches for an instance of the class `Person`\nwith a certain last name in an unsorted sequence of persons\nusing a `while` (and not `find`/`indexOf`).\n The function's return type should be `Option`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=S%C3%B6kning",
    "a program that registers 1000 dice rolls in an `Array`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Registrering",
    "a function `copy` that copies an `Array` of integers\nelement by element to a new `Array`\nthat uses a while statement in the implementation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Algoritm:%20SEQ-COPY",
    "a function `insert` that given an `Array` of integers\ninserts an element at a certain position\nthat uses a while statement in the implementation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20SEQ-INSERT/REMOVE-COPY",
    "a function that determines whether two strings are equal\nthat uses a while statement in the implementation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=J%C3%A4mf%C3%B6ra%20str%C3%A4ngar:%20likhet"
  ),
  Week(8) -> Concepts(
    "matrix",
    "nested structure",
    "type parameter",
    "generic function"
  ),
  Week(8) -> Contrasts(
    "matrix" -> "vector",
    "generic data structure" -> "generic function"
  ),
  Week(8) -> Code(
    "a generic function that takes a function `f` of type A => B, a function `g` of type B => C and an argument x of type A and returns g(`f(x)`)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Generisk%20funktion",
    "a function that takes a matrix of type `Vector[Vector[Int]]` and a column index and returns the column at that index as a `Vector`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20indexera%20i%20matriser?",
    "a function that with the help of nested for expressions sums all integers in a matrix of type `Vector[Vector[Int]]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "a function that counts the number of elements in a matrix of type `Vector[Vector[Int]]` that are even" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "a generic function that with a type parameter counts how many elements in a matrix of type `Vector[Vector[T]]` satisfy a given predicate" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Generisk%20funktion",
    "a function that with the help of `Vector.tabulate` builds a matrix with m rows and n columns where the element at position i,j has the value i times n plus j" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20skapa%20matriser?",
    "a function that with the help of `Vector.fill` builds a square matrix of size n times n where all elements are zero" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20skapa%20matriser?",
    "a generic function that transposes a matrix of type `Vector[Vector[T]]` so that rows swap places with columns" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "a function that returns the largest integer in a matrix of type `Vector[Vector[Int]]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "a predicate that with the help of `forall` determines whether all elements in a matrix of type `Vector[Vector[Int]]` are positive" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20indexera%20i%20matriser?",
    "a generic function that gives the main diagonal as a `Vector` from a square matrix of type `Vector[Vector[T]]` (the main diagonal = the elements where the row index equals the column index)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "a generic function that returns row r as a `Vector` from a matrix of type `Vector[Vector[T]]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "a generic function that takes a value x and an integer n and returns a `Vector` with n copies of x" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Generisk%20funktion",
    "a generic function that takes a pair of type (A, B) and returns the pair with the components in reverse order" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Generisk%20funktion",
    "a function that prints a string matrix row by row" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Iterera%20%C3%B6ver%20n%C3%A4stlad%20struktur",
    "a predicate that tests whether a nested sequence of integers\nis a mathematical matrix with m rows and n columns\nwith and without the help of the existing method `forall` (i.e. all rows have the same number of elements)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20indexera%20i%20matriser?"
  ),
  Week(9) -> Concepts(
    "set",
    "key-value table",
    "membership test",
    "serialization",
    "persistence"
  ),
  Week(9) -> Contrasts(
    "set" -> "sequence",
    "set" -> "key-value table",
    "key-value table" -> "sequence"
  ),
  Week(9) -> Code(
    "a function that takes a string with words separated by spaces and returns the number of unique words using `split` and `toSet`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20m%C3%A4ngd?",
    "a set that contains the colors red, green and blue and an expression that with `apply` determines whether yellow is in the set" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20m%C3%A4ngd?",
    "a set that is created from a number sequence with duplicates and an expression that gives the number of unique numbers" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20m%C3%A4ngd?",
    "a function that takes two integer sets and returns their intersection" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Of%C3%B6r%C3%A4nderlig%20m%C3%A4ngd",
    "a function that takes two string sets and returns their union" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Of%C3%B6r%C3%A4nderlig%20m%C3%A4ngd",
    "a function that takes a sequence of strings and returns the set of the strings that are longer than three characters" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Konvertera%20mellan%20olika%20samlingstyper",
    "a function that takes a sequence of integers and returns the number of numbers that occur more than once" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20m%C3%A4ngd?",
    "a key-value table that maps three fruits to their price and an expression that looks up the price of banana" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Den%20fantastiska%20nyckel-v%C3%A4rde-tabellen%20Map",
    "a function that takes a table and a key and returns the value, or zero if the key is missing, using `getOrElse`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Of%C3%B6r%C3%A4nderlig%20nyckel-v%C3%A4rde-tabell",
    "a function that takes a sequence of animal names and returns a table that maps each name to its length in number of characters" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Fr%C3%A5n%20sekvens%20av%20par%20till%20tabell",
    "a function that takes a table with integer values and returns a new table where all values have been doubled" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Fler%20exempel%20nyckel-v%C3%A4rde-tabell",
    "a key-value table that starts from an existing table and gives a new table where a pair has been added" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Of%C3%B6r%C3%A4nderlig%20nyckel-v%C3%A4rde-tabell",
    "a function that takes a table and returns a string where the pairs are serialized with `mkString`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Serialisering%20och%20deserialisering",
    "a function `readPersonSet` that reads in lines with comma-separated last names and first names from a text file\nand creates a set of instances of the case class `Person` and throws an exception if there are duplicates" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%A4sa%20text%20fr%C3%A5n%20fil%20och%20webbsida",
    "a function `readPersonMap` that reads in lines with comma-separated last names and first names and personal identity numbers from a text file\nand creates a key-value table with the personal identity number of type `Long` as key and instances of the case class `Person` as value" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%A4sa%20text%20fr%C3%A5n%20fil%20och%20webbsida",
    "a function that groups a sequence of words into a key-value table\nby word length using `groupBy`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Metoderna%20zipWithIndex,%20groupBy",
    "a function that with `sliding` computes the average of each pair\nof adjacent numbers in a number sequence" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Metoden%20sliding",
    "a key-value table that is created from a sequence of pairs (name, age)\nusing `toMap`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Fr%C3%A5n%20sekvens%20av%20par%20till%20tabell"
  ),
  Week(10) -> Concepts(
    "inheritance",
    "subtype polymorphism",
    "base type",
    "`final` member",
    "protected member (`protected`)",
    "overriding (`override`)",
    "dynamic binding",
    "code duplication",
    "anonymous class"
  ),
  Week(10) -> Contrasts(
    "subtype" -> "supertype",
    "class" -> "`trait`",
    "inheritance" -> "composition",
    "abstract member" -> "concrete member",
    "static type" -> "dynamic type"
  ),
  Week(10) -> Code(
    "a function that returns one of several subtypes to a common base type and thereby demonstrates subtype polymorphism" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "a class that through mixin combines several traits to reuse common members" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Inmixning",
    "a `trait` that has an abstract method and two concrete subtypes that implement it differently, as well as a function that receives the base type and calls the method polymorphically" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "a base type `Vehicle` with an abstract attribute maxSpeed and three subtypes that each give a value, as well as a `Vector` with mixed vehicles whose max speeds are summed" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "a subtype that with `override` replaces a concrete method in its supertype and calls `super` to reuse the supertype's behavior" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20%C3%96verskuggning%20och%20override",
    "a subtype that with `override` replaces a concrete method in its supertype without calling `super`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20%C3%96verskuggning%20och%20override",
    "a class `Player` that through composition has an attribute that refers to an Account and delegates the method balance to the account" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20till%20arv:%20komposition",
    "a base type `Shape` with an abstract method `area` and the subtypes Square and Circle that implement area, as well as a `Vector` of Shape whose areas are summed polymorphically" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "a `trait` `Account` that has a protected variable balance and a concrete method `deposit` that increases the balance, as well as a subtype that reads the balance" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Protected%20ger%20synlighet%20begr%C3%A4nsad%20till%20subtyper",
    "a supertype that has a `final` method that cannot be overridden and a subtype that inherits the final method" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=En%20final%20medlem%20kan%20ej%20%C3%B6verskuggas",
    "a `trait` `Animal` that has an abstract attribute sound and a concrete method `makeSound` that prints the sound, as well as two case classes that inherit the trait" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=En%20trait%20kan%20ha%20abstrakta%20medlemmar",
    "a base type `Message` with an abstract method `format` and the subtypes Sms and Email, as well as a function that takes a `Vector` of Message and prints all formatted" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "an anonymous class that directly at instantiation fills in the abstract method greeting in a `trait` `Greeter`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anonym%20klass",
    "a class `Thermometer` that through composition has an attribute Sensor and delegates the method `read` to the sensor instead of inheriting it" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20till%20arv:%20komposition",
    "a common base type (`trait`) for different vegetables with an abstract member for weight,\nand code that puts several vegetables in a sequence and sums the weight" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Skapa%20en%20gemensam%20bastyp%20med%20trait%20och%20extends",
    "a subclass that overrides a method with `override`\nand calls the supertype's version with `super`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20%C3%96verskuggning%20och%20override",
    "a class that is rewritten from using inheritance to instead using composition" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20till%20arv:%20komposition"
  )
)
