package shared

lazy val termsSv = Seq[(Week, Concepts | Contrasts | Code)](
  Week(1) -> Concepts(
    "funktion",
    "while-sats",
    "for-sats",
    "stränginterpolator",
    "tilldelning",
    "kompilering",
    "grundtyper",
    "booleskt värde",
    "exekvering i sekvens",
    "abstraktion"
  ),
  Week(1) -> Contrasts(
    "while-sats" -> "for-sats",
    "typ" -> "värde",
    "if-uttryck" -> "if-sats",
    "`def`" -> "`val`",
    "`var`" -> "`val`",
    "kompileringsfel" -> "körtidsfel",
    "`Char`" -> "`String`",
    "källkod" -> "maskinkod"
  ),
  Week(1) -> Code(
    "en funktion `dubblera` som tar ett heltal och ger tillbaka talet multiplicerat med två" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion,%20argument,%20parameter",
    "en funktion `kvadrat` som tar ett heltal n och ger n upphöjt till två" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion,%20argument,%20parameter",
    "ett uttryck som beräknar resten när 41 delas med 2 med operatorn %" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "ett uttryck som beräknar heltalsdelen av 41 dividerat med 2" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "ett booleskt uttryck som är sant precis när heltalet n är delbart med 3" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "ett booleskt uttryck som är sant precis när age ligger mellan 13 och 19" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "ett if-uttryck som ger strängen \"godkänt\" om poäng är minst 50, annars \"underkänt\"" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20med%20if-uttryck",
    "ett uttryck som konkatenerar strängarna \"gurk\" och \"burk\" till en enda sträng" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering",
    "ett uttryck som upprepar strängen \"ha\" 10 gånger med operatorn *" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering",
    "ett uttryck som räknar ut cirkelarean givet radien av r (cirkelns area är π·r², π finns som `math.Pi`)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Definiera%20namn%20p%C3%A5%20uttryck",
    "ett booleskt uttryck som är sant om x är större än noll eller x är mindre än -42" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20med%20if-uttryck",
    "en repetition som skriver ut de första 42 heltalen" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kontrollstrukturer:%20alternativ%20och%20repetition",
    "ett uttryck som beräknar summan av talen 7 och 5" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "ett uttryck som beräknar produkten av talen 9 och 6" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "ett uttryck som beräknar resten när 100 delas med 7" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "givet ett heltal n, ett uttryck som ger n ökat med ett" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "givet ett heltal n, ett uttryck som ger n upphöjt till två" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "givet ett heltal n, ett uttryck som ger den sista siffran i n" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Heltalsaritmetik",
    "givet två heltal a och b, ett uttryck som ger deras medelvärde som `Double`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Flyttalsaritmetik",
    "givet en radie r, ett uttryck som ger cirkelns omkrets (cirkelns omkrets är 2·π·r)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Flyttalsaritmetik",
    "givet bredd b och höjd h, ett uttryck som ger rektangelns area" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Flyttalsaritmetik",
    "givet grader Celsius c, ett uttryck som ger motsvarande temperatur i Fahrenheit (Fahrenheit = Celsius · 9/5 + 32)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Flyttalsaritmetik",
    "givet ett heltal n, ett booleskt uttryck som är sant om n är jämnt" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "givet en ålder i år, ett booleskt uttryck som är sant om personen är myndig (myndig = minst 18 år)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "givet en temperatur, ett booleskt uttryck som är sant om det är minusgrader" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "givet två heltal a och b, ett booleskt uttryck som är sant om de är lika" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "givet ett heltal n, ett booleskt uttryck som är sant om n är delbart med både 2 och 3" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Logiska%20uttryck",
    "givet ett förnamn och ett efternamn, ett uttryck som sätter ihop dem till ett namn med ett mellanslag emellan" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering",
    "givet ett namn, ett uttryck som med en stränginterpolator bygger hälsningen \"Hej <namn>!\"" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering",
    "givet en sträng s, ett uttryck som ger strängen s upprepad tre gånger" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Att%20bygga%20str%C3%A4ngar:%20konkatenering%20och%20interpolering"
  ),
  Week(2) -> Concepts(
    "for-uttryck",
    "indexering",
    "kontrollstruktur",
    "huvudprogram"
  ),
  Week(2) -> Contrasts(
    "pseudokod" -> "exekverbar implementation",
    "parameter" -> "argument",
    "returtyp" -> "parametertyp",
    "for-uttryck" -> "for-sats",
    "`Vector`" -> "`Array`"
  ),
  Week(2) -> Code(
    "ett program som skriver ut antalet negativa heltal i args" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Algoritmexempel:%20MIN",
    "en funktion som med en while-loop returnerar produkten av alla heltal i en `Array[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "ett uttryck som med for-yield bygger en ny `Vector` där varje tal i xs har ökats med 10" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Bygg%20ny%20samling%20fr%C3%A5n%20befintlig%20med%20for-yield-uttryck",
    "en funktion som med ett for-yield-uttryck returnerar kvadraten av varje tal i en `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Bygg%20ny%20samling%20fr%C3%A5n%20befintlig%20med%20for-yield-uttryck",
    "ett program som med en for-do-sats skriver ut varje element i args på en egen rad tillsammans med dess platsnummer" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20med%20Range",
    "en funktion som med en while-loop räknar antalet element i en `Array[Int]` som är jämnt delbara med 3" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "ett uttryck som med `Range` och for-yield skapar en `Vector` med de tio första udda talen" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Samlingen%20Range%20h%C3%A5ller%20reda%20p%C3%A5%20intervall",
    "en funktion som med for-yield returnerar en ny `Vector[String]` där varje sträng i en `Vector` har fått ett utropstecken tillagt på slutet" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Bygg%20ny%20samling%20fr%C3%A5n%20befintlig%20med%20for-yield-uttryck",
    "ett program som med @main tar emot ett heltal n och resten som strängar och skriver ut de n sista strängarna" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Typs%C3%A4kra%20argument%20till%20ett%20program%20med%20@main",
    "en funktion som med en while-loop returnerar medelvärdet av talen i en `Array[Int]` eller noll om arrayen är tom" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Algoritmexempel:%20MIN",
    "ett uttryck som med `Range` och sum beräknar summan av alla jämna tal från 0 till och med 100" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20med%20Range%20skapad%20med%20to",
    "en funktion som med en for-do-sats och en var-variabel räknar hur många gånger talet noll förekommer i en `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "ett program som byter plats på det andra och det näst sista elementet i args och skriver ut resultatet med blanktecken emellan" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20Array?",
    "en funktion som med indexering och en while-loop returnerar indexet för det första negativa talet i en `Array[Int]` eller minus ett om inget finns" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Algoritmexempel:%20MIN",
    "en funktion som ger minsta heltalet i en heltalssekvens,\nutan att använda inbyggda min" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "en funktion som ger största heltalet i en heltalssekvens,\nutan att använda inbyggda max" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "två förändringsbara variabler som först initialiseras\nmed två olika helatal och sedan byter värde med varandra" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20algoritm?",
    "en funktion som summerar alla heltal i en sekvens,\nutan att använda inbyggda sum" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20elementen%20i%20en%20vektor",
    "en repetition som med en for-sats skriver ut kvadraten av talen 1 till 10" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20med%20Range",
    "en repetition som med en while-sats skriver ut talen från 10 ner till 1" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "en repetition som kastar 100 tärningar och räknar antalet ettor" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats"
  ),
  Week(3) -> Concepts(
    "anonym funktion",
    "predikat",
    "äkta funktion",
    "aktiveringspost",
    "anropsstacken",
    "defaultargument",
    "returtyp",
    "namngivna argument",
    "lokal funktion",
    "funktion som äkta värde",
    "samlingsmetoden `map`"
  ),
  Week(3) -> Contrasts(
    "överlagring" -> "defaultargument",
    "namngivna argument" -> "defaultargument",
    "`map`" -> "`foreach`",
    "värdeanrop" -> "namnanrop"
  ),
  Week(3) -> Code(
    "ett predikat som avgör om en sträng är ett palindrom, det vill säga läses likadant framlänges och baklänges" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "en funktion som returnerar produkten av två heltal" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "en funktion som beräknar arean av en rektangel utifrån bredd och höjd och returnerar en `Double`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "en funktion som hälsar på en person genom att returnera strängen \"Hej \" följt av ett namn, med defaultargument \"världen\"" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktioner%20med%20defaultargument",
    "en funktion som upphöjer ett heltal till en exponent med defaultargument 2" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktioner%20med%20defaultargument",
    "en funktion som returnerar en formaterad adress utifrån parametrarna gata, nummer och postort och anropar den med namngivna argument i valfri ordning" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktioner%20med%20namngivna%20argument",
    "en anonym funktion som dubblerar ett heltal och applicerar den på alla element i `Vector(1, 2, 3)` med `map`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Applicera%20anonyma%20funktioner%20p%C3%A5%20element%20i%20samlingar",
    "en anonym funktion som lägger till ett utropstecken efter en sträng och applicerar den på `Vector(\"hej\", \"hå\")` med `map`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Applicera%20anonyma%20funktioner%20p%C3%A5%20element%20i%20samlingar",
    "en anonym funktion med platshållarsyntax som tredubblar ett heltal och applicerar den på `Vector(1, 2, 3)` med `map`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Platsh%C3%A5llarsyntax%20f%C3%B6r%20anonyma%20funktioner",
    "ett predikat som avgör om ett heltal är jämnt" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "ett predikat som avgör om en sträng är tom och filtrerar `Vector(\"a\", \"\", \"b\")` med `filter`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "ett predikat som avgör om ett heltal är positivt och delar upp `Vector(-2, 3, -1, 5)` med `partition`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "en högre ordningens funktion som applicerar en `given` funktion av typ `Int` => `Int` tre gånger på ett heltal" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktionsv%C3%A4rden%20kan%20vara%20argument",
    "en funktion med två parameterlistor som adderar två heltal och anropar den med båda argumenten" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Multipla%20parameterlistor",
    "en rekursiv funktion som beräknar fakulteten av ett heltal (fakulteten n! = 1·2·…·n, och 0! = 1)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Rekursiva%20funktioner",
    "en anonym funktion `Int` => `Int` som ger kvadraten och som appliceras på alla element i en heltalssekvens" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anonyma%20funktioner",
    "en definition av en oäkta funktion som returnerar slumpmässiga jämna heltal mellan n och m" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel%20p%C3%A5%20o%C3%A4kta%20funktioner:%20slumptal",
    "en funktion `roll` som ger ett slumpmässigt heltal mellan 1 och 6" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel%20p%C3%A5%20o%C3%A4kta%20funktioner:%20slumptal",
    "en funktion `omkrets` som tar en radie av typen `Double` och ger cirkelns omkrets (cirkelns omkrets är 2·π·r)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "en funktion `isAdult` som tar en ålder av typen `Int` och ger `true` om åldern är minst 18, annars `false`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "en funktion `medelvärde` som tar två decimaltal och ger deras genomsnitt" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "en funktion `isFreezing` som tar en temperatur och ger `true` om den är under noll" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "en funktion `areaRektangel` som tar bredd och höjd och ger rektangelns area" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "en funktion `celsiusTillFahrenheit` som omvandlar grader Celsius till Fahrenheit (Fahrenheit = Celsius · 9/5 + 32)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Funktion:%20deklaration%20och%20anrop",
    "en funktion `isEven(n: Int)` som är sann om n är ett jämt tal" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn"
  ),
  Week(4) -> Concepts(
    "singelobjekt",
    "paket",
    "privat medlem",
    "namnrymd",
    "metoden `apply`",
    "tupel",
    "`import`",
    "punktnotation",
    "extensionsmetod",
    "classpath"
  ),
  Week(4) -> Contrasts(
    "`val`" -> "`lazy` `val`",
    "`def`" -> "`lazy` `val`"
  ),
  Week(4) -> Code(
    "en extensionsmetod som lägger till metoderna inc och dec på heltal så att talet ökas respektive minskas med ett" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%A4gg%20till%20metoder%20i%20efterhand%20med%20extension",
    "ett typalias Pt för tupeltypen (`Int`, `Int`) och en funktion som tar två punkter av typen Pt och returnerar deras s.k. manhattanavstånd, definierat som summan av absolutbeloppen av differenserna mellan respektive koordinater, alltså i matematisk notation: |x1 - x2| + |y1 - y2| " -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Typalias%20f%C3%B6r%20att%20abstrahera%20typnamn",
    "ett singelobjekt som heter `mittBankkonto` med ett oföränderligt kontonr, ett föränderligt saldo och ett predikat `ärSkuldsatt` som är sant då saldot är negativt" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20singelobjektet%20med%20f%C3%B6r%C3%A4ndringsbart%20tillst%C3%A5nd",
    "ett singelobjekt som heter `Räknare` med en privat variabel _antal som börjar på noll, en getter antal och en metod `öka` som ökar räknaren med ett" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Inkapsling:%20att%20d%C3%B6lja%20interna%20delar",
    "ett singelobjekt som heter `Termostat` med en privat variabel _temp, en getter temp och en metod `höj` som ökar temperaturen med ett givet antal grader" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Inkapsling:%20att%20d%C3%B6lja%20interna%20delar",
    "en funktion som heter `längd` och tar en 2-tupel (`Double`, `Double`) som parameter och ger avståndet till origo med `math.hypot`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "en funktion som heter `polär` och tar en 2-tupel (`Double`, `Double`) och returnerar en 2-tupel med längd och vinkel beräknade med `math.hypot` och `math.atan2`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "en funktion som heter `mittpunkt` och tar två 2-tupler (`Double`, `Double`) och returnerar en 2-tupel med medelvärdet av x-koordinaterna och medelvärdet av y-koordinaterna" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "en funktion som heter `delaUpp` och tar en heltalssekvens och returnerar en 2-tupel med de jämna talen i första elementet och de udda i andra" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "ett typalias som heter `Pt` för typen (`Int`, `Int`) och en funktion `distToOrigo` som tar ett Pt och ger avståndet till origo med `math.hypot`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Typalias%20f%C3%B6r%20att%20abstrahera%20typnamn",
    "en extensionsmetod som heter `kvadrat` på typen `Int` och som ger talet multiplicerat med sig självt" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%A4gg%20till%20metoder%20i%20efterhand%20med%20extension",
    "kollektiva extensionsmetoder på typen `Double` med halva som ger talet delat med två och dubbla som ger talet gånger två, samlade under en och samma `extension`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kollektiva%20extensionsmetoder",
    "ett singelobjekt som heter `Färger` och som med namnbyte vid `import` gör `java.awt.Color` tillgänglig som JColor" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Namnbyte%20vid%20import",
    "en lat variabel som med `lazy` `val` fördröjer initialiseringen av en stor vektor tills den refereras första gången" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Lata%20variabler%20med%20f%C3%B6rdr%C3%B6jd%20initialisering",
    "ett par som med metoden -> kopplar strängen \"Ålder\" till talet 42, samt en vektor med tre sådana par" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Ett%20smidigt%20s%C3%A4tt%20att%20skapa%202-tupler%20med%20metoden%20->",
    "ett singelobjekt `Highscore` med en privat variabel för högsta poäng,\nen getter, en metod `isHighscore(p: Int)` och en metod `update(p: Int)` som ändrar tillståndet" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20singelobjektet%20med%20f%C3%B6r%C3%A4ndringsbart%20tillst%C3%A5nd",
    "en funktion som tar en punkt som en 2-tupel (`Double`, `Double`)\noch returnerar en ny 2-tupel förändrad på valfritt vis, och visa hur man kommer åt delarna med punktnotation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Tupler%20som%20parametrar%20och%20returv%C3%A4rde.",
    "en extensionsmetod på `String` som ger strängen baklänges och med versaler,\noch anropa den både med punktnotation och som en vanlig funktion" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kollektiva%20extensionsmetoder"
  ),
  Week(5) -> Concepts(
    "klass",
    "attribut",
    "fabriksmetod",
    "instansiering",
    "tillstånd",
    "klassparameter",
    "kompanjonsobjekt",
    "nyckelordet this",
    "strängrepresentation"
  ),
  Week(5) -> Contrasts(
    "funktion" -> "metod",
    "klass" -> "case-klass",
    "singelobjekt" -> "klass",
    "getter" -> "setter",
    "referenslikhet" -> "innehållslikhet"
  ),
  Week(5) -> Code(
    "en case-klass som modellerar en bok med titel, författare och antal sidor, samt en metod som returnerar en ny kopia med en sida tillagd" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "en case-klass som modellerar en temperatur i Celsius med ett härlett attribut som ger motsvarande värde i Fahrenheit (Fahrenheit = Celsius · 9/5 + 32)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "en case-klass som modellerar ett rektangulärt rum med bredd och höjd och ett härlett attribut som ger arean" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "en case-klass som modellerar ett bankkonto med ägare och saldo, samt en metod som returnerar en ny kopia med ett insatt belopp adderat till saldot" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "en case-klass som modellerar en vektor i två dimensioner med dx och dy och ett härlett attribut som ger längden med `math.hypot`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Klassen%20Complex",
    "en klass som har klassparametrarna förnamn, efternamn och stad och en egen `toString` som ger en snygg strängrepresentation med stränginterpolering" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Skapa%20egen%20najs%20toString",
    "en klass som har klassparametrarna titel och längd i minuter för en film och en egen `toString` som visar tillståndet med stränginterpolering" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Skapa%20egen%20najs%20toString",
    "en klass som har en klassparameter namn och en förändringsbar klassparameter poäng med defaultargument noll samt en egen `toString`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%B6sning:%20klassen%20Person",
    "ett kompanjonsobjekt som innehåller en fabriksmetod `apply` vilken skapar en instans av en oföränderlig klass med privat konstruktor" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kompanjonsobjekt%20med%20indirekt%20instansiering",
    "ett kompanjonsobjekt som innehåller en oföränderlig delad `val` som anger en standardfärg gemensam för alla instanser av klassen" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Attribut%20i%20kompanjonsobjekt%20anv%C3%A4ndas%20f%C3%B6r%20s%C3%A5dant%20som%20%C3%A4r%20gemensamt%20f%C3%B6r%20alla%20instanser",
    "en klass som har ett privat attribut för saldo och en setter som med `require` förhindrar negativa värden" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=F%C3%B6rhindra%20felaktiga%20attributv%C3%A4rden%20med%20setters",
    "en klass som har ett privat attribut för procentvärde och en getter samt en setter som bara tillåter värden mellan noll och hundra" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Getters%20och%20setters%20i%20Scala",
    "en case-klass som modellerar ett datum med år, månad och dag och en metod som returnerar en ny kopia med dagen ökad med ett" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "en case-klass som modellerar en cirkel med radie och ett härlett attribut som ger arean med `math.Pi` (arean är π·r²)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Datamodellering",
    "en klass som modellerar en räknare med ett privat attribut och metoder för att öka med ett och avläsa nuvarande värde" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Getters%20och%20setters%20i%20Scala",
    "en case-klass som modellerar en spelare med namn och liv och en metod som returnerar en ny kopia med ett liv borttaget" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Case-klasser%20%C3%A4r%20som%20vanliga%20klasser%20med%20extra%20godis",
    "en klass `Person` med klassparametrar för förnamn, efternamn och ålder\noch en egen `toString` som ger en läsbar strängrepresentation" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Skapa%20egen%20najs%20toString",
    "en oföränderlig case-klass `Point` och förklara skillnaden mellan == och eq,\noch använd `copy` för att skapa en delvis förändrad kopia" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20of%C3%B6r%C3%A4nderliga%20case-klassen%20Point",
    "en klass med en privat variabel för ålder som skyddas av en getter\noch en setter som förhindrar negativa värden" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=F%C3%B6rhindra%20felaktiga%20attributv%C3%A4rden%20med%20setters"
  ),
  Week(6) -> Concepts(
    "mönstermatchning",
    "undantag",
    "konstruktormönster",
    "`Option`",
    "`Try`",
    "förseglad typ"
  ),
  Week(6) -> Contrasts(
    "`Try`" -> "try-catch",
    "förseglad (`sealed`) typhierarki" -> "ej förseglad typhierarki"
  ),
  Week(6) -> Code(
    "en funktion som med ett match-uttryck tar en `Vector` av strängar och returnerar tom om den är tom, det enda elementet baklänges om den har ett element, annars första och sista elementet sammanfogade" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Plocka%20is%C3%A4r%20samlingar%20med%20djupa%20m%C3%B6nster",
    "en funktion som med ett match-uttryck tar en tupel av två heltal och returnerar lika om talen är lika, växer om det första är mindre än det andra, annars minskar" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20p%C3%A5%20tupler",
    "ett match-uttryck som tar en sträng dag och returnerar helg om värdet är lördag eller söndag, annars vardag, med konstant-mönster och en wildcard-gren" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kolla%20om%20det%20passar%20med%20match-uttryck",
    "ett match-uttryck som tar ett heltalsbetyg och returnerar underkänd för 0, 1, 2, godkänd för 3, 4 och väl godkänd för 5, med eller-mönster och en wildcard-gren sist" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20med%20eller-m%C3%B6nster",
    "en funktion som med ett match-uttryck och garder returnerar negativt om n är mindre än noll, noll om n är noll och positivt annars" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20med%20gard",
    "ett match-uttryck som matchar ett tärningsslag och returnerar sexa med en gard, annars binder ett variabelmönster och returnerar slaget" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20med%20variabelm%C3%B6nster",
    "en funktion som med typade mönster tar ett värde av typen `Any` och returnerar olika strängar beroende på om värdet är en `Int`, en `String` eller något annat" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20med%20typade%20m%C3%B6nster",
    "en case-klass `Punkt` och en funktion som med ett konstruktormönster returnerar på axeln om punkten ligger på en axel, annars i planet" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Konstruktorm%C3%B6nster%20med%20case-klasser",
    "ett match-uttryck som plockar isär en tupel av namn och ålder och med en gard returnerar olika strängar för jämn respektive udda ålder" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Matchning%20p%C3%A5%20tupler",
    "en förseglad bastyp `Väderstreck` med fyra case-objekt och en funktion som med ett match-uttryck returnerar det motsatta väderstrecket" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=M%C3%B6nstermatchning%20och%20f%C3%B6rseglade%20typer",
    "en enumeration `Trafikljus` och en funktion som med ett match-uttryck returnerar nästa ljus i ordningen" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=M%C3%B6nstermatcha%20enumeration",
    "en funktion som med `getOrElse` returnerar värdet i en `Option` om det finns, annars strängen \"saknas\"" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20smidiga%20metoder%20p%C3%A5%20Option",
    "en funktion som med ett match-uttryck på `Some` och `None` beskriver om ett Option-värde finns eller saknas" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Option%20f%C3%B6r%20hantering%20av%20ev.%20saknade%20v%C3%A4rden",
    "en funktion som med `map` fördubblar värdet i en `Option` om det finns, annars ger `None`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20smidiga%20metoder%20p%C3%A5%20Option",
    "en funktion som med `require` kräver att argumentet inte är negativt innan den returnerar kvadratroten" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Orsaka%20undantag%20indirekt%20med%20require%20och%20assert",
    "en funktion som med `throw` kastar ett undantag om ett uttag är större än saldot, annars returnerar nytt saldo" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Kasta%20undantag%20direkt%20med%20primitiva%20throw",
    "ett try-catch-uttryck som beräknar en heltalsdivision och fångar ett ArithmeticException genom att returnera minus ett" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Primitiva%20try-catch-uttryck",
    "en funktion som med ett try-catch-uttryck slår upp ett element på ett index och fångar ett IndexOutOfBoundsException genom att returnera noll" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Primitiva%20try-catch-uttryck",
    "en funktion som med ett match-uttryck på `Success` och `Failure` beskriver resultatet av ett `Try`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hantera%20undantag%20som%20ett%20v%C3%A4rde%20med%20Try",
    "en förseglad (`sealed`) typhierarki av grönsaker och en funktion som med\nmönstermatchning och en gard klassificerar en grönsak (uttömmande matchning)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=M%C3%B6nstermatchning%20och%20f%C3%B6rseglade%20typer",
    "en funktion som slår upp ett värde i en nyckel-värde-tabell och ger ett\nstandardvärde om nyckeln saknas, och en variant som mönstermatchar på `Some` och `None`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Option%20f%C3%B6r%20hantering%20av%20ev.%20saknade%20v%C3%A4rden",
    "en funktion som tolkar en sträng till ett heltal och fångar eventuellt fel\nmed `Try`, och en variant som använder try-catch" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hantera%20undantag%20som%20ett%20v%C3%A4rde%20med%20Try"
  ),
  Week(7) -> Concepts(
    "pseudokod",
    "sekvensalgoritm",
    "filtrering",
    "transformering",
    "registrering",
    "att ändra på plats",
    "likhet mellan strängar",
    "sorterad sekvens av strängar",
    "enumeration",
    "linjärsökning",
    "insättningssortering",
    "repeterade parametrar"
  ),
  Week(7) -> Contrasts(
    "`ArrayBuffer`" -> "`Array`",
    "förändringsbar samling" -> "oföränderlig samling",
    "skapa ny sekvens" -> "ändra på plats",
    "uppräknade värden med heltal" -> "uppräknade värden med `enum`",
    "`List`" -> "`ListBuffer`"
  ),
  Week(7) -> Code(
    "ett `enum` `Väderstreck` med fallen Norr, Öster, Söder och Väster och en funktion som med mönstermatchning ger det motsatta väderstrecket" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enum%20och%20m%C3%B6nster-matchning",
    "ett `enum` `Mynt` där varje fall har ett valörvärde i ören som parameter och en metod som ger värdet i kronor som `Double` (1 krona = 100 öre)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enumerationer%20kan%20ha%20parametrar%20och%20medlemmar",
    "en funktion som med metoden `filter` ger en ny vektor med bara de positiva heltalen ur en `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anv%C3%A4nda%20samlingsmetoden%20filter%20f%C3%B6r%20filtrering",
    "en funktion som med metoden `filter` ger en ny vektor med bara de strängar som är längre än tre tecken ur en `Vector[String]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anv%C3%A4nda%20samlingsmetoden%20filter%20f%C3%B6r%20filtrering",
    "en funktion som med metoden `map` ger en ny vektor där varje heltal i en `Vector[Int]` har dubblerats" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Implementation%20av%20sekvensproblem%20med%20map,%20filter",
    "en funktion som med metoden `map` ger en ny vektor med längden av varje sträng i en `Vector[String]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Implementation%20av%20sekvensproblem%20med%20map,%20filter",
    "en funktion som med metoden `count` räknar antalet jämna heltal i en `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20anv%C3%A4ndbara%20samlingsmetoder%20vid%20implementation%20av%20sekvensalgoritmer",
    "en funktion som med metoden `find` ger det första elementet i en `Vector[String]` som börjar med bokstaven a" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20anv%C3%A4ndbara%20samlingsmetoder%20vid%20implementation%20av%20sekvensalgoritmer",
    "en funktion som med ett for-uttryck och en gard ger en ny vektor med bara de heltal i en `Vector[Int]` som är delbara med tre" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anv%C3%A4nda%20for-uttryck%20f%C3%B6r%20filtrering%20med%20hj%C3%A4lp%20av%20gard",
    "en funktion som med en while-sats räknar och returnerar antalet negativa heltal i en `Vector[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "en funktion som med en while-sats ger summan av alla heltal i en `Array[Int]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Loopa%20genom%20en%20samling%20med%20en%20while-sats",
    "ett `enum` som räknar upp de fyra årstiderna Vår, Sommar, Höst och Vinter" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enumerationer%20har%20en%20ordning",
    "ett `enum` som heter `Trafikljus` med fallen Röd, Gul och Grön och en parameter stannar av typen `Boolean` där Röd och Gul stannar men Grön inte gör det" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enumerationer%20kan%20ha%20parametrar%20och%20medlemmar",
    "ett `enum` som heter `Planet` med en parameter massa av typen `Double` och en medlemsmetod som ger massan dubblerad" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Enumerationer%20kan%20ha%20parametrar%20och%20medlemmar",
    "en funktion med repeterade parametrar av typen `Int` som ger antalet argument som är större än noll" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Repeterade%20parametrar%20blir%20sekvens",
    "en funktion med repeterade parametrar av typen `Double` som ger medelvärdet av argumenten" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Repeterade%20parametrar%20blir%20sekvens",
    "ett predikat som tar två strängar och ger `true` om de börjar med samma bokstav" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Predikat,%20med%20och%20utan%20namn",
    "en funktion som med metoden `sortBy` ger en ny vektor med strängarna i en `Vector[String]` sorterade efter sin längd" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=N%C3%A5gra%20anv%C3%A4ndbara%20samlingsmetoder%20vid%20implementation%20av%20sekvensalgoritmer",
    "en funktion som med metoden `sortWith` ger en ny vektor med heltalen i en `Vector[Int]` sorterade från störst till minst" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Sortera%20till%20ny%20samling%20med%20godtyckligt%20ordningspredikat",
    "en funktion som linjärsöker efter en instans av klassen `Person`\nmed ett visst efternamn i en osorterad sekvens av personer\nmed hjälp av en `while` (och inte `find`/`indexOf`).\n Funktionens returtyp ska vara `Option`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=S%C3%B6kning",
    "ett program som registrerar 1000 tärningskast i en `Array`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Registrering",
    "en funktion `copy` som kopierar en `Array` med heltal\nelement för element till en ny `Array`\nsom använder en while-sats i implementationen" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Algoritm:%20SEQ-COPY",
    "en funktion `insert` som givet en `Array` med heltal\nstoppar in ett element på en viss plats\nsom använder en while-sats i implementationen" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20SEQ-INSERT/REMOVE-COPY",
    "en funktion som avgör om två strängar är lika\nsom använder en while-sats i implementationen" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=J%C3%A4mf%C3%B6ra%20str%C3%A4ngar:%20likhet"
  ),
  Week(8) -> Concepts(
    "matris",
    "nästlad struktur",
    "typparameter",
    "generisk funktion"
  ),
  Week(8) -> Contrasts(
    "matris" -> "vektor",
    "generisk datastruktur" -> "generisk funktion"
  ),
  Week(8) -> Code(
    "en generisk funktion som tar en funktion `f` av typ A => B, en funktion `g` av typ B => C och ett argument x av typ A och returnerar g(`f(x)`)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Generisk%20funktion",
    "en funktion som tar en matris av typen `Vector[Vector[Int]]` och ett kolumnindex och returnerar kolonnen på det indexet som en `Vector`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20indexera%20i%20matriser?",
    "en funktion som med hjälp av nästlade for-uttryck summerar alla heltal i en matris av typen `Vector[Vector[Int]]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "en funktion som räknar antalet element i en matris av typen `Vector[Vector[Int]]` som är jämna" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "en generisk funktion som med en typparameter räknar hur många element i en matris av typen `Vector[Vector[T]]` som uppfyller ett givet predikat" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Generisk%20funktion",
    "en funktion som med hjälp av `Vector.tabulate` bygger en matris med m rader och n kolumner där elementet på plats i,j har värdet i gånger n plus j" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20skapa%20matriser?",
    "en funktion som med hjälp av `Vector.fill` bygger en kvadratisk matris av storlek n gånger n där alla element är noll" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20skapa%20matriser?",
    "en generisk funktion som transponerar en matris av typen `Vector[Vector[T]]` så att rader byter plats med kolumner" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "en funktion som returnerar det största heltalet i en matris av typen `Vector[Vector[Int]]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "ett predikat som med hjälp av `forall` avgör om alla element i en matris av typen `Vector[Vector[Int]]` är positiva" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20indexera%20i%20matriser?",
    "en generisk funktion som ger huvuddiagonalen som en `Vector` ur en kvadratisk matris av typen `Vector[Vector[T]]` (huvuddiagonalen = elementen där radindex är lika med kolumnindex)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "en generisk funktion som returnerar rad r som en `Vector` ur en matris av typen `Vector[Vector[T]]`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Indexering%20i%20en%20matris",
    "en generisk funktion som tar emot ett värde x och ett heltal n och returnerar en `Vector` med n kopior av x" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Generisk%20funktion",
    "en generisk funktion som tar ett par av typen (A, B) och returnerar paret med komponenterna i omvänd ordning" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20Generisk%20funktion",
    "en funktion som skriver ut en strängmatris rad för rad" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Iterera%20%C3%B6ver%20n%C3%A4stlad%20struktur",
    "ett predikat som testar om en nästlad sekvens av heltal\när en matematisk matris med m rader och n kolumner\nmed och utan hjälp av befintliga metoden `forall` (dvs. alla rader har lika många element)" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Hur%20indexera%20i%20matriser?"
  ),
  Week(9) -> Concepts(
    "mängd",
    "nyckel-värde-tabell",
    "innehållstest",
    "serialisering",
    "persistens"
  ),
  Week(9) -> Contrasts(
    "mängd" -> "sekvens",
    "mängd" -> "nyckel-värde-tabell",
    "nyckel-värde-tabell" -> "sekvens"
  ),
  Week(9) -> Code(
    "en funktion som tar en sträng med ord separerade av blanksteg och returnerar antalet unika ord med hjälp av `split` och `toSet`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20m%C3%A4ngd?",
    "en mängd som innehåller färgerna röd, grön och blå och ett uttryck som med `apply` avgör om gul finns i mängden" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20m%C3%A4ngd?",
    "en mängd som skapas ur en talsekvens med dubbletter och ett uttryck som ger antalet unika tal" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20m%C3%A4ngd?",
    "en funktion som tar två heltalsmängder och returnerar deras snitt" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Of%C3%B6r%C3%A4nderlig%20m%C3%A4ngd",
    "en funktion som tar två strängmängder och returnerar deras union" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Of%C3%B6r%C3%A4nderlig%20m%C3%A4ngd",
    "en funktion som tar en sekvens av strängar och returnerar mängden av de strängar som är längre än tre tecken" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Konvertera%20mellan%20olika%20samlingstyper",
    "en funktion som tar en sekvens av heltal och returnerar antalet tal som förekommer mer än en gång" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Vad%20%C3%A4r%20en%20m%C3%A4ngd?",
    "en nyckel-värde-tabell som mappar tre frukter till deras pris och ett uttryck som slår upp priset på banan" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Den%20fantastiska%20nyckel-v%C3%A4rde-tabellen%20Map",
    "en funktion som tar en tabell och en nyckel och returnerar värdet, eller noll om nyckeln saknas, med hjälp av `getOrElse`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Of%C3%B6r%C3%A4nderlig%20nyckel-v%C3%A4rde-tabell",
    "en funktion som tar en sekvens av djurnamn och returnerar en tabell som mappar varje namn till dess längd i antal tecken" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Fr%C3%A5n%20sekvens%20av%20par%20till%20tabell",
    "en funktion som tar en tabell med heltalsvärden och returnerar en ny tabell där alla värden har dubblerats" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Fler%20exempel%20nyckel-v%C3%A4rde-tabell",
    "en nyckel-värde-tabell som utgår från en befintlig tabell och ger en ny tabell där ett par har lagts till" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Of%C3%B6r%C3%A4nderlig%20nyckel-v%C3%A4rde-tabell",
    "en funktion som tar en tabell och returnerar en sträng där paren är serialiserade med `mkString`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Serialisering%20och%20deserialisering",
    "en funktion `readPersonSet` som läser in rader med kommaseparerade efternamn och förnamn från en textfil\noch skapar en mängd av instanser av case-klassen `Person` och kastar ett undantag om det finns dubbletter" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%A4sa%20text%20fr%C3%A5n%20fil%20och%20webbsida",
    "en funktion `readPersonMap` som läser in rader med kommaseparerade efternamn och förnamn och personnummer från en textfil\noch skapar en nyckel-värde-tabell med personnummer av typen `Long` som nyckel och instanser av case-klassen `Person` som värde" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=L%C3%A4sa%20text%20fr%C3%A5n%20fil%20och%20webbsida",
    "en funktion som grupperar en sekvens av ord i en nyckel-värde-tabell\nefter ordlängd med hjälp av `groupBy`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Metoderna%20zipWithIndex,%20groupBy",
    "en funktion som med `sliding` beräknar medelvärdet av varje par\nav intilliggande tal i en talsekvens" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Metoden%20sliding",
    "en nyckel-värde-tabell som skapas från en sekvens av par (namn, ålder)\nmed hjälp av `toMap`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Fr%C3%A5n%20sekvens%20av%20par%20till%20tabell"
  ),
  Week(10) -> Concepts(
    "arv",
    "subtypspolymorfism",
    "bastyp",
    "`final` medlem",
    "skyddad medlem (`protected`)",
    "överskuggning (`override`)",
    "dynamisk bindning",
    "kod-duplicering",
    "anonym klass"
  ),
  Week(10) -> Contrasts(
    "subtyp" -> "supertyp",
    "klass" -> "`trait`",
    "arv" -> "komposition",
    "abstrakt medlem" -> "konkret medlem",
    "statisk typ" -> "dynamisk typ"
  ),
  Week(10) -> Code(
    "en funktion som returnerar en av flera subtyper till en gemensam bastyp och på så vis visar subtypspolymorfism" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "en klass som genom inmixning kombinerar flera traits för att återanvända gemensamma medlemmar" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Inmixning",
    "en `trait` som har en abstrakt metod och två konkreta subtyper som implementerar den olika, samt en funktion som tar emot bastypen och anropar metoden polymorft" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "en bastyp `Fordon` med ett abstrakt attribut maxfart och tre subtyper som ger varsitt värde, samt en `Vector` med blandade fordon vars maxfarter summeras" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "en subtyp som med `override` ersätter en konkret metod i sin supertyp och anropar `super` för att återanvända supertypens beteende" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20%C3%96verskuggning%20och%20override",
    "en subtyp som med `override` ersätter en konkret metod i sin supertyp utan att anropa `super`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20%C3%96verskuggning%20och%20override",
    "en klass `Spelare` som genom komposition har ett attribut som refererar till ett Konto och vidaredelegerar metoden saldo till kontot" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20till%20arv:%20komposition",
    "en bastyp `Form` med en abstrakt metod `area` och subtyperna Kvadrat och Cirkel som implementerar area, samt en `Vector` av Form vars areor summeras polymorft" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "en `trait` `Konto` som har en skyddad variabel saldo och en konkret metod `sättIn` som ökar saldot, samt en subtyp som läser saldot" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Protected%20ger%20synlighet%20begr%C3%A4nsad%20till%20subtyper",
    "en supertyp som har en `final` metod som ej kan överskuggas och en subtyp som ärver den finala metoden" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=En%20final%20medlem%20kan%20ej%20%C3%B6verskuggas",
    "en `trait` `Djur` som har ett abstrakt attribut läte och en konkret metod `låter` som skriver ut lätet, samt två case-klasser som ärver traiten" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=En%20trait%20kan%20ha%20abstrakta%20medlemmar",
    "en bastyp `Meddelande` med en abstrakt metod `formatera` och subtyperna Sms och Epost, samt en funktion som tar en `Vector` av Meddelande och skriver ut alla formaterade" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Subtypspolymorfism%20och%20dynamisk%20bindning",
    "en anonym klass som direkt vid instansiering fyller i den abstrakta metoden hälsning i en `trait` `Hälsare`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Anonym%20klass",
    "en klass `Termometer` som genom komposition har ett attribut Sensor och delegerar metoden `läsAv` till sensorn i stället för att ärva den" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20till%20arv:%20komposition",
    "en gemensam bastyp (`trait`) för olika grönsaker med en abstrakt medlem för vikt,\noch kod som lägger flera grönsaker i en sekvens och summerar vikten" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Skapa%20en%20gemensam%20bastyp%20med%20trait%20och%20extends",
    "en subklass som överskuggar en metod med `override`\noch anropar supertypens version med `super`" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Exempel:%20%C3%96verskuggning%20och%20override",
    "en klass som skrivs om från att använda arv till att i stället använda komposition" -> "https://fileadmin.cs.lth.se/pgk/compendium.pdf#nameddest=Alternativ%20till%20arv:%20komposition"
  )
)
