package shared

  lazy val headingsWithPageAndLevel: Seq[(String, Int, Int)] = Seq(
    ("Framstegsprotokoll", 3, 1),
    ("Förord", 5, 1),
    ("I Om kursen", 7, 1),
    ("Kursens arkitektur", 8, 2),
    ("Veckoöversikt", 8, 3),
    ("Om ditt lärande", 11, 3),
    ("Vad lär du dig?", 11, 4),
    ("Progression", 11, 4),
    ("Hur lär du dig?", 11, 4),
    ("Kursmoment — varför?", 12, 4),
    ("En typisk kursvecka", 13, 4),
    ("Anvisningar", 14, 2),
    ("Samarbetsgrupper", 14, 3),
    ("Samarbetskontrakt", 15, 4),
    ("Grupplaboration", 15, 4),
    ("Föreläsningar", 16, 3),
    ("Övningar", 16, 3),
    ("Resurstider", 18, 3),
    ("Laborationer", 18, 3),
    ("Projektuppgift", 20, 3),
    ("Muntligt prov", 21, 3),
    ("Valfri tentamen", 21, 3),
    ("Hur bidra till kursmaterialet?", 22, 2),
    ("Bidrag är varmt välkomna!", 22, 3),
    ("Instruktioner", 22, 3),
    ("Vad behövs för att kunna bidra?", 22, 4),
    ("Svenska eller engelska?", 22, 4),
    ("Exempel", 23, 3),
    ("II Moduler", 26, 1),
    ("Introduktion", 27, 2),
    ("Teori Prog", 28, 3),
    ("Hur fungerar en dator?", 28, 4),
    ("Vad är programmering?", 28, 4),
    ("Vad är en kompilator?", 28, 4),
    ("Virtuell maskin (VM) == abstrakt hårdvara", 29, 4),
    ("Vad består ett program av?", 29, 4),
    ("Exempel på programmeringsspråk", 30, 4),
    ("Olika programmeringsparadigm", 30, 4),
    ("Hello world", 30, 4),
    ("Utvecklingscykeln", 31, 4),
    ("Utvecklingsverktyg", 31, 4),
    ("Installera verktyg på din egen dator", 32, 4),
    ("Scala Command Line Interface (CLI)", 32, 4),
    ("Tips och trix med scala i terminalen", 32, 4),
    ("Litteraler", 33, 4),
    ("Exempel på inbyggda datatyper i Scala", 33, 4),
    ("Grundtyper i Scala", 33, 4),
    ("Grundtypernas omfång", 34, 4),
    ("Uttryck", 34, 4),
    ("Variabler", 35, 4),
    ("Regler för identifierare", 35, 4),
    ("Att bygga strängar", 36, 4),
    ("Heltalsaritmetik", 36, 4),
    ("Flyttalsaritmetik", 37, 4),
    ("Definiera namn på uttryck", 37, 4),
    ("Funktion, argument, parameter", 37, 4),
    ("Färdiga matte-funktioner i paketet scala.math", 38, 4),
    ("Logiska uttryck", 38, 4),
    ("De Morgans lagar", 39, 4),
    ("Alternativ med if-uttryck", 39, 4),
    ("Uttryck eller sats?", 39, 4),
    ("Variabeldeklaration och tilldelningssats", 40, 4),
    ("Tilldelningssatser är inte matematisk likhet", 40, 4),
    ("Förkortade tilldelningssatser", 40, 4),
    ("Exempel på förkortade tilldelningssatser", 41, 4),
    ("Variabler som ändrar värden kan vara knepiga", 41, 4),
    ("Kontrollstrukturer", 41, 4),
    ("Scala-2-syntax för kontrollstrukturer fungerar i Scala 3", 42, 4),
    ("Repetera många satser", 42, 4),
    ("Procedurer", 43, 4),
    ("Problemlösning", 43, 4),
    ("Övning expressions och labb kojo", 43, 4),
    ("Köa med Sigrid", 44, 4),
    ("Sigrid in action", 44, 4),
    ("Datorer och datoranvändning", 45, 3),
    ("Välkommen till Datorer och datoranvändning (dod)", 45, 4),
    ("Förberedelse Lab 1", 45, 4),
    ("Operativsystem", 45, 4),
    ("Unix historia", 46, 4),
    ("Linux och GNU", 46, 4),
    ("Kännetecken för Unix", 46, 4),
    ("Filer i Unix/Linux", 46, 4),
    ("Kataloger", 47, 4),
    ("Filnamn och sökvägar", 47, 4),
    ("Förkortade filnamn", 48, 4),
    ("Kommandotolk (shell, skal) och terminal", 48, 4),
    ("Kommandotolk (shell, skal) och terminal", 48, 4),
    ("Bash vs. Zsh för Mac-användare", 49, 4),
    ("Unix-shellalternativ för Windows-användare", 49, 4),
    ("Kommandoformat", 50, 4),
    ("Kommandon för filhantering", 50, 4),
    ("Kataloghantering", 50, 4),
    ("Filskydd 1/3", 51, 4),
    ("Filskydd 2/3", 51, 4),
    ("Filskydd 3/3", 51, 4),
    ("bash-finesser 1", 52, 4),
    ("bash-finesser 2", 52, 4),
    ("Initieringsfiler", 53, 4),
    ("Vad är egentligen ett kommando?", 53, 4),
    ("Processer", 53, 4),
    ("Fönstersystem, skrivbordsmiljö", 54, 4),
    ("Övning expressions", 55, 3),
    ("Grunduppgifter; förberedelse inför laboration", 56, 4),
    ("Extrauppgifter; träna mer", 63, 4),
    ("Fördjupningsuppgifter; utmaningar", 66, 4),
    ("Laboration", 69, 3),
    ("Obligatoriska uppgifter", 69, 4),
    ("Kontrollfrågor", 72, 4),
    ("Frivilliga extrauppgifter", 73, 4),
    ("Laboration", 79, 3),
    ("Datorarbete", 80, 4),
    ("Program, kontrollstrukturer, maskinkod", 83, 2),
    ("Teori", 84, 3),
    ("Vad är en datastruktur?", 84, 4),
    ("Några samlingar i scala.collection", 84, 4),
    ("Olika strukturer för att hantera data", 85, 4),
    ("Vad är en vektor?", 85, 4),
    ("En konceptuell bild av en vektor", 85, 4),
    ("En samling strängar", 86, 4),
    ("Vad är en kontrollstruktur?", 86, 4),
    ("Loopa genom elementen i en vektor", 87, 4),
    ("Bygg ny samling från befintlig med for-yield-uttryck", 87, 4),
    ("Samlingen Range håller reda på intervall", 87, 4),
    ("Loopa med Range", 88, 4),
    ("Loopa med Range skapad med to", 88, 4),
    ("Loopa genom en samling med en while-sats", 88, 4),
    ("Vad är en Array?", 89, 4),
    ("Några likheter & skillnader mellan Vector och Array", 89, 4),
    ("Ett minimalt fristående program i Scala", 89, 4),
    ("Typsäkra argument till ett program med @main", 90, 4),
    ("Vad är en algoritm?", 90, 4),
    ("Algoritmexempel", 90, 4),
    ("Algoritmexempel", 91, 4),
    ("Mall för funktionsdefinitioner", 91, 4),
    ("Bättre många små abstraktioner som gör en sak var", 92, 4),
    ("Vad är ett block?", 92, 4),
    ("Namn i block blir lokala", 92, 4),
    ("Parameter och argument", 93, 4),
    ("Procedurer", 93, 4),
    ("Ingenting är faktiskt någonting i Scala", 94, 4),
    ("Problemlösning", 94, 4),
    ("Exempel på funktionell nedbrytning", 94, 4),
    ("Varför abstraktion?", 95, 4),
    ("Från källkod till maskinkod med JVM", 95, 4),
    ("Paket", 95, 4),
    ("Import", 96, 4),
    ("Jar-filer", 96, 4),
    ("Övning programs", 97, 3),
    ("Grunduppgifter", 97, 4),
    ("Extrauppgifter; träna mer", 102, 4),
    ("Fördjupningsuppgifter; utmaningar", 104, 4),
    
  )
