package shared

  lazy val headingsWithPageAndLevel: Seq[(String, Int, Int)] = Seq(
    ("Framstegsprotokoll", 3, 1),
    ("Förord", 5, 1),
    ("I Om kursen", 7, 1),
    ("Kursens arkitektur", 8, 2),
    ("Veckoöversikt", 8, 3),
    ("Om ditt lärande", 11, 3),
    ("Vad lär du dig?", 11, 4),
    ("Progression", 11, 4),
    ("Hur lär du dig?", 11, 4),
    ("Kursmoment — varför?", 12, 4),
    ("En typisk kursvecka", 13, 4),
    ("Anvisningar", 14, 2),
    ("Samarbetsgrupper", 14, 3),
    ("Samarbetskontrakt", 15, 4),
    ("Grupplaboration", 15, 4),
    ("Föreläsningar", 16, 3),
    ("Övningar", 16, 3),
    ("Resurstider", 18, 3),
    ("Laborationer", 18, 3),
    ("Projektuppgift", 20, 3),
    ("Muntligt prov", 21, 3),
    ("Valfri tentamen", 21, 3),
    ("Hur bidra till kursmaterialet?", 22, 2),
    ("Bidrag är varmt välkomna!", 22, 3),
    ("Instruktioner", 22, 3),
    ("Vad behövs för att kunna bidra?", 22, 4),
    ("Svenska eller engelska?", 22, 4),
    ("Exempel", 23, 3),
    ("II Moduler", 26, 1),
    ("Introduktion", 27, 2),
    ("Teori programmering", 28, 3),
    ("Hur fungerar en dator?", 28, 4),
    ("Vad är programmering?", 28, 4),
    ("Vad är en kompilator?", 28, 4),
    ("Virtuell maskin (VM) == abstrakt hårdvara", 29, 4),
    ("Vad består ett program av?", 29, 4),
    ("Exempel på programmeringsspråk", 30, 4),
    ("Olika programmeringsparadigm", 30, 4),
    ("Hello world", 30, 4),
    ("Utvecklingscykeln", 31, 4),
    ("Utvecklingsverktyg", 31, 4),
    ("Installera verktyg på din egen dator", 32, 4),
    ("Scala Command Line Interface (CLI)", 32, 4),
    ("Tips och trix med scala i terminalen", 32, 4),
    ("Litteraler", 33, 4),
    ("Exempel på inbyggda datatyper i Scala", 33, 4),
    ("Grundtyper i Scala", 33, 4),
    ("Grundtypernas omfång", 34, 4),
    ("Uttryck", 34, 4),
    ("Variabler", 35, 4),
    ("Regler för identifierare", 35, 4),
    ("Att bygga strängar", 36, 4),
    ("Heltalsaritmetik", 36, 4),
    ("Flyttalsaritmetik", 37, 4),
    ("Definiera namn på uttryck", 37, 4),
    ("Funktion, argument, parameter", 37, 4),
    ("Färdiga matte-funktioner i paketet scala.math", 38, 4),
    ("Logiska uttryck", 38, 4),
    ("De Morgans lagar", 39, 4),
    ("Alternativ med if-uttryck", 39, 4),
    ("Uttryck eller sats?", 39, 4),
    ("Variabeldeklaration och tilldelningssats", 40, 4),
    ("Tilldelningssatser är inte matematisk likhet", 40, 4),
    ("Förkortade tilldelningssatser", 40, 4),
    ("Exempel på förkortade tilldelningssatser", 41, 4),
    ("Variabler som ändrar värden kan vara knepiga", 41, 4),
    ("Kontrollstrukturer", 41, 4),
    ("Scala-2-syntax för kontrollstrukturer fungerar i Scala 3", 42, 4),
    ("Repetera många satser", 42, 4),
    ("Procedurer", 43, 4),
    ("Problemlösning", 43, 4),
    ("Övning expressions och labb kojo", 43, 4),
    ("Köa med Sigrid", 44, 4),
    ("Sigrid in action", 44, 4),
    ("Teori datorer och datoranvändning", 45, 3),
    ("Välkommen till Datorer och datoranvändning (dod)", 45, 4),
    ("Förberedelse Lab 1", 45, 4),
    ("Operativsystem", 45, 4),
    ("Unix historia", 46, 4),
    ("Linux och GNU", 46, 4),
    ("Kännetecken för Unix", 46, 4),
    ("Filer i Unix/Linux", 46, 4),
    ("Kataloger", 47, 4),
    ("Filnamn och sökvägar", 47, 4),
    ("Förkortade filnamn", 48, 4),
    ("Kommandotolk (shell, skal) och terminal", 48, 4),
    ("Kommandotolk (shell, skal) och terminal", 48, 4),
    ("Bash vs. Zsh för Mac-användare", 49, 4),
    ("Unix-shellalternativ för Windows-användare", 49, 4),
    ("Kommandoformat", 50, 4),
    ("Kommandon för filhantering", 50, 4),
    ("Kataloghantering", 50, 4),
    ("Filskydd 1/3", 51, 4),
    ("Filskydd 2/3", 51, 4),
    ("Filskydd 3/3", 51, 4),
    ("bash-finesser 1", 52, 4),
    ("bash-finesser 2", 52, 4),
    ("Initieringsfiler", 52, 4),
    ("Vad är egentligen ett kommando?", 53, 4),
    ("Processer", 53, 4),
    ("Fönstersystem, skrivbordsmiljö", 54, 4),
    ("Övning expressions", 55, 3),
    ("Grunduppgifter; förberedelse inför laboration", 56, 4),
    ("Extrauppgifter; träna mer", 63, 4),
    ("Fördjupningsuppgifter; utmaningar", 66, 4),
    ("Laboration", 69, 3),
    ("Obligatoriska uppgifter", 69, 4),
    ("Kontrollfrågor", 72, 4),
    ("Frivilliga extrauppgifter", 73, 4),
    ("Laboration", 79, 3),
    ("Datorarbete", 80, 4),
    ("Program, kontrollstrukturer, maskinkod", 83, 2),
    ("Teori programmering", 84, 3),
    ("Vad är en datastruktur?", 84, 4),
    ("Några samlingar i scala.collection", 84, 4),
    ("Olika strukturer för att hantera data", 85, 4),
    ("Vad är en vektor?", 85, 4),
    ("En konceptuell bild av en vektor", 86, 4),
    ("En samling strängar", 86, 4),
    ("Vad är en kontrollstruktur?", 86, 4),
    ("Loopa genom elementen i en vektor", 87, 4),
    ("Bygg ny samling från befintlig med for-yield-uttryck", 87, 4),
    ("Samlingen Range håller reda på intervall", 87, 4),
    ("Loopa med Range", 88, 4),
    ("Loopa med Range skapad med to", 88, 4),
    ("Loopa genom en samling med en while-sats", 88, 4),
    ("Vad är en Array?", 89, 4),
    ("Några likheter & skillnader mellan Vector och Array", 89, 4),
    ("Ett minimalt fristående program i Scala", 90, 4),
    ("Typsäkra argument till ett program med @main", 90, 4),
    ("Vad är en algoritm?", 90, 4),
    ("Algoritmexempel", 91, 4),
    ("Algoritmexempel", 91, 4),
    ("Mall för funktionsdefinitioner", 91, 4),
    ("Bättre många små abstraktioner som gör en sak var", 92, 4),
    ("Vad är ett block?", 92, 4),
    ("Namn i block blir lokala", 93, 4),
    ("Parameter och argument", 93, 4),
    ("Procedurer", 93, 4),
    ("Ingenting är faktiskt någonting i Scala", 94, 4),
    ("Problemlösning", 94, 4),
    ("Exempel på funktionell nedbrytning", 95, 4),
    ("Varför abstraktion?", 95, 4),
    ("Från källkod till maskinkod med JVM", 96, 4),
    ("Paket", 96, 4),
    ("Import", 96, 4),
    ("Jar-filer", 97, 4),
    ("Teori datorer och datoranvändning", 98, 3),
    ("Bakgrund", 98, 4),
    ("Vad är en dator?", 98, 4),
    ("Binära tal - Introduktion", 98, 4),
    ("Binära tal - Varför?", 99, 4),
    ("Binära tal - I Datorer", 99, 4),
    ("Hexadecimala Tal", 100, 4),
    ("Central Processing Unit (CPU)", 100, 4),
    ("Minne i datorer", 100, 4),
    ("Maskinkod -- definition och egenskaper", 101, 4),
    ("Maskininstruktioner", 101, 4),
    ("Assembly-språk", 101, 4),
    ("Exempel på en assembly-instruktion", 102, 4),
    ("Instruktionsuppsättningsarkitektur (ISA)", 102, 4),
    ("Maskinkod vs. Högnivåspråk", 102, 4),
    ("Laboration -- c3pu", 103, 4),
    ("Vad är c3pu?", 103, 4),
    ("Övning programs", 104, 3),
    ("Grunduppgifter", 104, 4),
    ("Extrauppgifter; träna mer", 109, 4),
    ("Fördjupningsuppgifter; utmaningar", 111, 4),
    ("Laboration", 113, 3),
    ("Kort teori om maskinkod", 114, 4),
    ("Datorarbete", 115, 4),
    ("Extrauppgifter (frivilliga)", 118, 4),
    ("Funktioner och abstraktion", 121, 2),
    ("Teori", 122, 3),
    ("Vad är abstraktion?", 122, 4),
    ("Exempel på abstraktionsmekanismer inom datavetenskapen", 122, 4),
    ("Funktion", 122, 4),
    ("Deklarera funktioner, överlagring", 123, 4),
    ("Funktioner med defaultargument", 123, 4),
    ("Funktioner med namngivna argument", 123, 4),
    ("Enhetlig access", 124, 4),
    ("Anropsstacken och objektheapen", 124, 4),
    ("Anropsstacken och aktiveringsposter", 125, 4),
    ("Vad är en stack trace?", 125, 4),
    ("Hur läsa en stack trace?", 125, 4),
    ("Lokala funktioner", 126, 4),
    ("Funktioner är äkta värden i Scala", 126, 4),
    ("Funktionsvärden kan vara argument", 127, 4),
    ("Applicera funktioner på element i samlingar med map", 127, 4),
    ("Applicera funktioner på element i samlingar med map", 128, 4),
    ("Äkta funktioner", 128, 4),
    ("Exempel på oäkta funktioner", 128, 4),
    ("Slumptalsfrö", 129, 4),
    ("Anonyma funktioner", 129, 4),
    ("Applicera anonyma funktioner på element i samlingar", 130, 4),
    ("Platshållarsyntax för anonyma funktioner", 130, 4),
    ("Exempel på platshållarsyntax med reduceLeft", 130, 4),
    ("Predikat, med och utan namn", 131, 4),
    ("Funktionsvärde vid tom parameterlista", 131, 4),
    ("Hur fungerar egentligen upprepa i Kojo?", 132, 4),
    ("Multipla parameterlistor", 132, 4),
    ("Värdeanrop och namnanrop", 132, 4),
    ("Klammerparenteser vid ensam parameter", 133, 4),
    ("Skapa din egen kontrollstruktur", 133, 4),
    ("Kolon vid ensam parameter", 133, 4),
    ("Stegade funktioner, Curry-funktioner", 134, 4),
    ("Funktion med fångad variabelrymd", 134, 4),
    ("Rekursiva funktioner", 134, 4),
    ("Loopa med rekursion", 135, 4),
    ("Rekursiva datastrukturer", 135, 4),
    ("Kompilera om det som ändrats vid varje sparning", 136, 4),
    ("Övning functions", 137, 3),
    ("Grunduppgifter; förberedelse inför laboration", 137, 4),
    ("Extrauppgifter; träna mer", 141, 4),
    ("Fördjupningsuppgifter; utmaningar", 144, 4),
    ("Laboration", 147, 3),
    ("Krav", 147, 4),
    ("Tips för att komma igång", 147, 4),
    ("Inspiration", 148, 4),
    ("Objekt och inkapsling", 150, 2),
    ("Teori", 151, 3),
    ("Vad rymmer sköldpaddan i Kojo i sitt tillstånd?", 151, 4),
    ("Vad är ett objekt?", 151, 4),
    ("Deklarera, allokera, referera", 151, 4),
    ("Olika sätt att allokera objekt", 152, 4),
    ("Vad är ett singelobjekt?", 152, 4),
    ("Allokering", 153, 4),
    ("Punktnotation, tillståndsförändring med tilldelning", 153, 4),
    ("Punktnotation och operatornotation", 153, 4),
    ("Namnrymd och skuggning", 154, 4),
    ("Inkapsling", 154, 4),
    ("Idiom", 155, 4),
    ("Principen om enhetlig access", 155, 4),
    ("Exempel", 155, 4),
    ("Exempel", 156, 4),
    ("Tillståndsändring", 156, 4),
    ("Modul", 156, 4),
    ("Deklarera paket", 157, 4),
    ("Kompilera paket", 157, 4),
    ("Paket i REPL", 158, 4),
    ("Vad är en tupel?", 158, 4),
    ("Tupler som parametrar och returvärde.", 158, 4),
    ("Ett smidigt sätt att skapa 2-tupler med metoden ->", 159, 4),
    ("Typalias för att abstrahera typnamn", 159, 4),
    ("Lata variabler med fördröjd initialisering", 159, 4),
    ("Singelobjekt är lata", 160, 4),
    ("Vad är skillnaden mellan val, var, def, lazy val?", 160, 4),
    ("Fallgrop", 160, 4),
    ("Programmeringsparadigm", 161, 4),
    ("Funktioner är äkta objekt i Scala", 161, 4),
    ("Fördjupning", 161, 4),
    ("Vad är en klass?", 162, 4),
    ("Vad är en klass?", 162, 4),
    ("Använda klassen Color", 162, 4),
    ("Lägg till metoder i efterhand med extension", 163, 4),
    ("Kollektiva extensionsmetoder", 163, 4),
    ("Import av alla namn i en viss modul", 164, 4),
    ("Namnbyte vid import", 164, 4),
    ("Exkludera (gömma) namn vid import", 164, 4),
    ("Lokal import-deklaration", 165, 4),
    ("Export", 165, 4),
    ("Använda dokumentation för färdiga klasser.", 165, 4),
    ("Vad är en jar-fil?", 166, 4),
    ("Öppen källkod på Maven Central", 166, 4),
    ("Vad är classpath?", 166, 4),
    ("Färdiga grafikmetoder i klassen PixelWindow", 166, 4),
    ("Automatiska beroenden med Scala CLI i REPL", 167, 4),
    ("Köra program + kodbiblitek med Scala CLI", 167, 4),
    ("Kompilera om vid varje ändring", 168, 4),
    ("Övning objects", 169, 3),
    ("Grunduppgifter; förberedelse inför laboration", 169, 4),
    ("Extrauppgifter; träna mer", 176, 4),
    ("Fördjupningsuppgifter; utmaningar", 177, 4),
    ("Laboration", 180, 3),
    ("Bakgrund", 180, 4),
    ("Obligatoriska uppgifter", 180, 4),
    ("Kontrollfrågor", 185, 4),
    ("Frivilliga extrauppgifter", 185, 4),
    ("Klasser och datamodellering", 189, 2),
    ("Teori", 190, 3),
    ("En metafor för klass", 190, 4),
    ("Vad är en klass?", 190, 4),
    ("Datamodellering", 190, 4),
    ("Singelobjekt jämfört med klass", 191, 4),
    ("Förändring av objektets tillstånd", 191, 4),
    ("Bättre att initialisera med hjälp av klassparametrar", 191, 4),
    ("Klassdeklarationer och instansiering", 192, 4),
    ("Övning", 192, 4),
    ("Lösning", 193, 4),
    ("Skapa egen najs toString", 193, 4),
    ("Instansprivata klassparametrar", 194, 4),
    ("Case-klasser är som vanliga klasser med extra godis", 194, 4),
    ("Fördjupning", 195, 4),
    ("Styra användningen av infixa alfanumeriska operatorer", 195, 4),
    ("Övning", 195, 4),
    ("Exempel", 196, 4),
    ("Exempel", 196, 4),
    ("Instansiering med direkt användning av new", 197, 4),
    ("Indirekt instansiering med fabriksmetoder", 197, 4),
    ("Hur förhindra direkt instansiering?", 197, 4),
    ("Kompanjonsobjekt med indirekt instansiering", 198, 4),
    ("Användning av kompanjonsobjekt med fabriksmetoder", 198, 4),
    ("Alternativa direktinstansieringar med default-argument", 199, 4),
    ("Alternativa sätt att instansiera med fabriksmetod", 199, 4),
    ("Medlemmar som bara behövs i en enda upplaga", 199, 4),
    ("Medlemmar i singelobjekt är statiskt allokerade", 200, 4),
    ("Attribut i kompanjonsobjekt användas för sådant som är gemensamt för alla instanser", 200, 4),
    ("Övning", 201, 4),
    ("Case-klasser", 201, 4),
    ("Exempel", 201, 4),
    ("Vad är en konstruktor?", 202, 4),
    ("Fördjupning", 202, 4),
    ("Fördjupning", 202, 4),
    ("Referens saknas", 203, 4),
    ("Exempel", 203, 4),
    ("Defaultvärden under pågående konstruktion", 204, 4),
    ("Problem med initialisering av attribut vid konstruktion", 204, 4),
    ("Vilka värden har attribut medan konstruktion pågår?", 204, 4),
    ("Hur undvika initialiseringsproblem vid konstruktion?", 205, 4),
    ("Be kompilatorn att varna vid initialiseringsproblem", 205, 4),
    ("Be kompilatorn ge fler bra varningar", 206, 4),
    ("Referensen this", 206, 4),
    ("Getters och setters", 207, 4),
    ("Java-exempel", 207, 4),
    ("Motsvarande JPerson i Scala", 208, 4),
    ("Förhindra felaktiga attributvärden med setters", 208, 4),
    ("Getters och setters i Scala", 208, 4),
    ("Referenslikhet eller innehållslikhet?", 209, 4),
    ("Exempel", 209, 4),
    ("Referenslikhet och egna klasser", 210, 4),
    ("Case-klasser ger innehållslikhet", 210, 4),
    ("Likhet och case-klasser", 210, 4),
    ("Sammanfattning case-klass-godis", 210, 4),
    ("Implementation saknas", 211, 4),
    ("Exempel", 211, 4),
    ("Övning classes", 212, 3),
    ("Grunduppgifter; förberedelse inför laboration", 212, 4),
    ("Extrauppgifter; träna mer", 218, 4),
    ("Fördjupningsuppgifter; utmaningar", 222, 4),
    ("Laboration", 227, 3),
    ("Mönster och felhantering", 228, 2),
    ("Teori", 229, 3),
    ("Bastypen för alla typer", 229, 4),
    ("Alla typer är subtyper till Any", 229, 4),
    ("Dina egna referenstyper är subtyper till AnyRef", 229, 4),
    ("Vad är matchning?", 230, 4),
    ("Plocka isär ett objekt i sina beståndsdelar med mönster", 230, 4),
    ("Kolla om det passar med nästlade if-uttryck", 230, 4),
    ("Kolla om det passar med match-uttryck", 231, 4),
    ("Syntax för match-uttryck", 231, 4),
    ("Matchning med gard", 232, 4),
    ("Matchning med variabelmönster", 232, 4),
    ("Matchning med eller-mönster", 232, 4),
    ("Matchning med typade mönster", 233, 4),
    ("Fördjupning", 233, 4),
    ("Konstruktormönster med case-klasser", 234, 4),
    ("Plocka isär samlingar med djupa mönster", 234, 4),
    ("Matchning på tupler", 234, 4),
    ("Mönstermatchning och uppräkning med case-objekt", 235, 4),
    ("Mönstermatchning och förseglade typer", 235, 4),
    ("Mönstermatcha enumeration", 236, 4),
    ("Stora/små begynnelsebokstäver vid matchning", 236, 4),
    ("Stora/små begynnelsebokstäver vid matchning", 236, 4),
    ("Mönster på andra ställen än i match", 237, 4),
    ("Mönsterdelar och variabelt antal argument", 237, 4),
    ("Partiella funktioner och metoden collect", 237, 4),
    ("Fördjupning", 238, 4),
    ("Hur hantera saknade värden?", 238, 4),
    ("En gemensam bastyp för ett värde som kanske saknas", 239, 4),
    ("Option för hantering av ev. saknade värden", 239, 4),
    ("Några smidiga metoder på Option", 239, 4),
    ("Några samlingsmetoder som ger en Option, övning", 240, 4),
    ("Några samlingsmetoder som ger en Option, svar", 240, 4),
    ("Vad är ett undantag (eng. exception)?", 241, 4),
    ("Orsaka undantag indirekt med require och assert", 241, 4),
    ("Kasta undantag direkt med primitiva throw", 241, 4),
    ("En gemensam bastyp för något som kan misslyckas", 242, 4),
    ("Hantera undantag som ett värde med Try", 242, 4),
    ("Primitiva try-catch-uttryck", 243, 4),
    ("Undvik undantag om det går", 243, 4),
    ("Fördjupning", 244, 4),
    ("Fördjupning", 244, 4),
    ("Fördjupning", 244, 4),
    ("Fördjupning", 245, 4),
    ("Fördjupning", 245, 4),
    ("Övning patterns", 247, 3),
    ("Grunduppgifter; förberedelse inför laboration", 247, 4),
    ("Fördjupningsuppgifter; utmaningar", 252, 4),
    ("Laboration", 258, 3),
    ("Bakgrund", 259, 4),
    ("Obligatoriska krav", 259, 4),
    ("Valbara krav -- välj minst ett", 260, 4),
    ("Förberedelser inför redovisningen", 260, 4),
    ("Tips och förslag", 260, 4),
    ("Sekvenser och enumerationer", 263, 2),
    ("Teori", 264, 3),
    ("Vad är en sekvens?", 264, 4),
    ("Exempel", 264, 4),
    ("Iterera över element i en sekvens", 264, 4),
    ("Lägg till i början och i slutet av en sekvens", 265, 4),
    ("Egenskaper hos några sekvenssamlingar i Scala", 265, 4),
    ("Vilken sekvenssamling ska jag välja?", 266, 4),
    ("Några konstigheter med Array", 266, 4),
    ("Oföränderlig eller förändringsbar?", 267, 4),
    ("Vad är en sekvensalgoritm?", 267, 4),
    ("Använda färdiga sekvenssamlingsmetoder", 267, 4),
    ("Några användbara samlingsmetoder vid implementation av sekvensalgoritmer", 268, 4),
    ("Uppdaterad sekvens med kraftfulla metoden patch", 268, 4),
    ("Använda for-uttryck för filtrering med hjälp av gard", 268, 4),
    ("Använda samlingsmetoden filter för filtrering", 269, 4),
    ("Vanliga sekvensproblem som funktionshuvuden", 269, 4),
    ("Implementation av sekvensproblem med for-uttryck eller färdiga samlingsmetoder", 269, 4),
    ("Implementation av sekvensproblem med map, filter", 270, 4),
    ("Hierarki av samlingstyper i scala.collection v2.13", 270, 4),
    ("Lämna det öppet", 270, 4),
    ("Implementation med generiska funktioner", 271, 4),
    ("Fördjupning", 271, 4),
    ("Fördjupning", 272, 4),
    ("Repeterade parametrar blir sekvens", 272, 4),
    ("Sekvenssamling som argument till repeterade parametrar", 273, 4),
    ("Enumerationer har en ordning", 273, 4),
    ("Enumerationer kan ha parametrar och medlemmar", 273, 4),
    ("Enum kan motsvara fullfjädrade case-klasser", 274, 4),
    ("Enum och mönster-matchning", 274, 4),
    ("Fördelar med enum jämfört med uppräkning med heltal", 275, 4),
    ("Registrering", 275, 4),
    ("Registrering av tärningskast i Array", 276, 4),
    ("Registrering av tärningskast i Array", 276, 4),
    ("Skapa lösningar på sekvensproblem från grunden", 276, 4),
    ("Skapa ny sekvenssamling eller ändra på plats?", 277, 4),
    ("Algoritm", 277, 4),
    ("Implementation av SEQ-COPY med while", 277, 4),
    ("Typ-alias för att abstrahera typnamn", 278, 4),
    ("Exempel", 278, 4),
    ("Pseudo-kod för SEQ-INSERT-COPY", 279, 4),
    ("Insättning/borttagning i kopia av primitiv Array", 279, 4),
    ("Exempel", 279, 4),
    ("Implementera Polygon", 280, 4),
    ("Exempel", 280, 4),
    ("Exempel", 281, 4),
    ("Exempel", 281, 4),
    ("Att sortera och jämföra strängar lexikografiskt", 282, 4),
    ("Jämföra strängar", 282, 4),
    ("Algoritmexempel", 282, 4),
    ("Algoritmexempel", 283, 4),
    ("Jämföra strängar", 283, 4),
    ("Jämföra strängar", 283, 4),
    ("Jämföra strängar", 284, 4),
    ("Sökning", 284, 4),
    ("Linjärsökning", 285, 4),
    ("Sortering", 285, 4),
    ("Algoritmisk komplexitet", 286, 4),
    ("Det finns många olika sorteringsalgoritmer", 286, 4),
    ("Bogo sort", 286, 4),
    ("Sortera till ny vektor med insättningssortering", 286, 4),
    ("Sortera till ny vektor med insättningssortering", 287, 4),
    ("Sortera till ny samling med godtyckligt ordningspredikat", 287, 4),
    ("Insättningssortering på plats -- pseudo-kod", 288, 4),
    ("Insättningssortering på plats -- implementation", 288, 4),
    ("Övning sequences", 289, 3),
    ("Grunduppgifter; förberedelse inför laboration", 289, 4),
    ("Extrauppgifter; träna mer", 297, 4),
    ("Fördjupningsuppgifter; utmaningar", 300, 4),
    ("Laboration", 305, 3),
    ("Bakgrund", 305, 4),
    ("Given kod", 306, 4),
    ("Obligatoriska uppgifter", 306, 4),
    ("Frivilliga extrauppgifter", 310, 4),
    ("Bilder med exempel på olika pokerhänder", 310, 4),
    ("Nästlade och generiska strukturer, typsättning", 313, 2),
    ("Teori programmering", 314, 3),
    ("Veckans labb", 314, 4),
    ("Vad är en matris?", 314, 4),
    ("Indexering i en matris", 314, 4),
    ("Hur skapa matriser?", 315, 4),
    ("Hur indexera i matriser?", 315, 4),
    ("Hur indexera i matriser?", 316, 4),
    ("Uppdatering av en förändringsbar nästlad struktur", 316, 4),
    ("Uppdatering av en förändringsbar nästlad struktur", 316, 4),
    ("Några olika sätt att skapa förändringsbara matriser", 317, 4),
    ("Exempel på skapande av oföränderlig nästlad struktur", 317, 4),
    ("Exempel på skapande av oföränderlig nästlad struktur", 318, 4),
    ("Uppdatering av en oföränderlig nästlad struktur", 318, 4),
    ("Uppdatering av en oföränderlig nästlad struktur", 318, 4),
    ("Iterera över nästlad struktur", 319, 4),
    ("Iterera över nästlad struktur", 319, 4),
    ("Övningsexempel", 320, 4),
    ("Övningsexempel", 320, 4),
    ("Iterera över nästlad struktur", 320, 4),
    ("Iterera över nästlad struktur", 321, 4),
    ("Nästlade for-uttryck", 321, 4),
    ("Nästlade for-uttryck", 321, 4),
    ("Nästlade map-uttryck", 322, 4),
    ("Nästlade map-uttryck", 322, 4),
    ("Fallgrop", 322, 4),
    ("Kolla likhet mellan två heltalsmatriser (uppfinner hjulet)", 322, 4),
    ("Använd INTE sameElements på nästlade arrayer", 323, 4),
    ("Kontroll av innehållslikhet mellan nästlade arrayer", 323, 4),
    ("Exempel", 324, 4),
    ("Exempel", 324, 4),
    ("Vad är en typparameter?", 324, 4),
    ("Exempel", 325, 4),
    ("Exempel", 325, 4),
    ("Fallgrop", 326, 4),
    ("Debugging -- Appendix D", 326, 4),
    ("Den första buggen", 326, 4),
    ("Olika sorters fel?", 327, 4),
    ("När upptäcks fel?", 327, 4),
    ("Förebygga fel", 328, 4),
    ("Hitta felorsaken", 328, 4),
    ("Åtgärda fel", 328, 4),
    ("Använda en debugger", 329, 4),
    ("Teori", 330, 3),
    ("Ordbehandling", 330, 4),
    ("LaTeX - Arbetssätt och Exempel", 330, 4),
    ("Ett större exempel", 330, 4),
    ("Interaktiv Demonstration", 330, 4),
    
  )
