package shared

  lazy val headingsWithPageAndLevel: Seq[(String, Int, Int)] = Seq(
    ("Framstegsprotokoll", 3, 1),
    ("Förord", 5, 1),
    ("I Om kursen", 31, 1),
    ("Kursens arkitektur", 32, 2),
    ("Veckoöversikt", 32, 3),
    ("Om ditt lärande", 35, 3),
    ("Vad lär du dig?", 35, 4),
    ("Progression", 35, 4),
    ("Hur lär du dig?", 35, 4),
    ("Kursmoment — varför?", 36, 4),
    ("En typisk kursvecka", 37, 4),
    ("Anvisningar", 38, 2),
    ("Samarbetsgrupper", 38, 3),
    ("Samarbetskontrakt", 39, 4),
    ("Grupplaboration", 39, 4),
    ("Föreläsningar", 40, 3),
    ("Övningar", 40, 3),
    ("Resurstider", 42, 3),
    ("Laborationer", 42, 3),
    ("Projektuppgift", 44, 3),
    ("Muntligt prov", 45, 3),
    ("Valfri tentamen", 45, 3),
    ("Hur bidra till kursmaterialet?", 46, 2),
    ("Bidrag är varmt välkomna!", 46, 3),
    ("Instruktioner", 46, 3),
    ("Vad behövs för att kunna bidra?", 46, 4),
    ("Svenska eller engelska?", 46, 4),
    ("Exempel", 47, 3),
    ("II Moduler", 50, 1),
    ("Introduktion", 51, 2),
    ("Teori programmering", 52, 3),
    ("Hur fungerar en dator?", 52, 4),
    ("Vad är programmering?", 52, 4),
    ("Vad är en kompilator?", 52, 4),
    ("Virtuell maskin (VM) == abstrakt hårdvara", 53, 4),
    ("Vad består ett program av?", 53, 4),
    ("Exempel på programmeringsspråk", 54, 4),
    ("Olika programmeringsparadigm", 54, 4),
    ("Hello world", 54, 4),
    ("Utvecklingscykeln", 55, 4),
    ("Utvecklingsverktyg", 55, 4),
    ("Installera verktyg på din egen dator", 56, 4),
    ("Scala Command Line Interface (CLI)", 56, 4),
    ("Tips och trix med scala i terminalen", 56, 4),
    ("Litteraler", 57, 4),
    ("Exempel på inbyggda datatyper i Scala", 57, 4),
    ("Grundtyper i Scala", 57, 4),
    ("Grundtypernas omfång", 58, 4),
    ("Uttryck", 58, 4),
    ("Variabler", 59, 4),
    ("Regler för identifierare", 59, 4),
    ("Att bygga strängar", 60, 4),
    ("Heltalsaritmetik", 60, 4),
    ("Flyttalsaritmetik", 61, 4),
    ("Definiera namn på uttryck", 61, 4),
    ("Funktion, argument, parameter", 61, 4),
    ("Färdiga matte-funktioner i paketet scala.math", 62, 4),
    ("Logiska uttryck", 62, 4),
    ("De Morgans lagar", 63, 4),
    ("Alternativ med if-uttryck", 63, 4),
    ("Uttryck eller sats?", 63, 4),
    ("Variabeldeklaration och tilldelningssats", 64, 4),
    ("Tilldelningssatser är inte matematisk likhet", 64, 4),
    ("Förkortade tilldelningssatser", 64, 4),
    ("Exempel på förkortade tilldelningssatser", 65, 4),
    ("Variabler som ändrar värden kan vara knepiga", 65, 4),
    ("Kontrollstrukturer", 65, 4),
    ("Scala-2-syntax för kontrollstrukturer fungerar i Scala 3", 66, 4),
    ("Repetera många satser", 66, 4),
    ("Procedurer", 67, 4),
    ("Problemlösning", 67, 4),
    ("Övning expressions och labb kojo", 67, 4),
    ("Köa med Sigrid", 68, 4),
    ("Sigrid in action", 68, 4),
    ("Teori datorer och datoranvändning", 69, 3),
    ("Välkommen till Datorer och datoranvändning (dod)", 69, 4),
    ("Förberedelse Lab 1", 69, 4),
    ("Operativsystem", 69, 4),
    ("Unix historia", 70, 4),
    ("Linux och GNU", 70, 4),
    ("Kännetecken för Unix", 70, 4),
    ("Filer i Unix/Linux", 70, 4),
    ("Kataloger", 71, 4),
    ("Filnamn och sökvägar", 71, 4),
    ("Förkortade filnamn", 72, 4),
    ("Kommandotolk (shell, skal) och terminal", 72, 4),
    ("Kommandotolk (shell, skal) och terminal", 72, 4),
    ("Bash vs. Zsh för Mac-användare", 73, 4),
    ("Unix-shellalternativ för Windows-användare", 73, 4),
    ("Kommandoformat", 74, 4),
    ("Kommandon för filhantering", 74, 4),
    ("Kataloghantering", 74, 4),
    ("Filskydd 1/3", 75, 4),
    ("Filskydd 2/3", 75, 4),
    ("Filskydd 3/3", 75, 4),
    ("bash-finesser 1", 76, 4),
    ("bash-finesser 2", 76, 4),
    ("Initieringsfiler", 76, 4),
    ("Vad är egentligen ett kommando?", 77, 4),
    ("Processer", 77, 4),
    ("Fönstersystem, skrivbordsmiljö", 78, 4),
    ("Övning expressions", 79, 3),
    ("Grunduppgifter; förberedelse inför laboration", 80, 4),
    ("Extrauppgifter; träna mer", 87, 4),
    ("Fördjupningsuppgifter; utmaningar", 90, 4),
    ("Laboration", 93, 3),
    ("Obligatoriska uppgifter", 93, 4),
    ("Kontrollfrågor", 96, 4),
    ("Frivilliga extrauppgifter", 97, 4),
    ("Laboration", 103, 3),
    ("Datorarbete", 104, 4),
    ("Program, kontrollstrukturer, maskinkod", 107, 2),
    ("Teori programmering", 108, 3),
    ("Vad är en datastruktur?", 108, 4),
    ("Några samlingar i scala.collection", 108, 4),
    ("Olika strukturer för att hantera data", 109, 4),
    ("Vad är en vektor?", 109, 4),
    ("En konceptuell bild av en vektor", 110, 4),
    ("En samling strängar", 110, 4),
    ("Vad är en kontrollstruktur?", 110, 4),
    ("Loopa genom elementen i en vektor", 111, 4),
    ("Bygg ny samling från befintlig med for-yield-uttryck", 111, 4),
    ("Samlingen Range håller reda på intervall", 111, 4),
    ("Loopa med Range", 112, 4),
    ("Loopa med Range skapad med to", 112, 4),
    ("Loopa genom en samling med en while-sats", 112, 4),
    ("Vad är en Array?", 113, 4),
    ("Några likheter & skillnader mellan Vector och Array", 113, 4),
    ("Ett minimalt fristående program i Scala", 114, 4),
    ("Typsäkra argument till ett program med @main", 114, 4),
    ("Vad är en algoritm?", 114, 4),
    ("Algoritmexempel", 115, 4),
    ("Algoritmexempel", 115, 4),
    ("Mall för funktionsdefinitioner", 115, 4),
    ("Bättre många små abstraktioner som gör en sak var", 116, 4),
    ("Vad är ett block?", 116, 4),
    ("Namn i block blir lokala", 117, 4),
    ("Parameter och argument", 117, 4),
    ("Procedurer", 117, 4),
    ("Ingenting är faktiskt någonting i Scala", 118, 4),
    ("Problemlösning", 118, 4),
    ("Exempel på funktionell nedbrytning", 119, 4),
    ("Varför abstraktion?", 119, 4),
    ("Från källkod till maskinkod med JVM", 120, 4),
    ("Paket", 120, 4),
    ("Import", 120, 4),
    ("Jar-filer", 121, 4),
    ("Teori datorer och datoranvändning", 122, 3),
    ("Bakgrund", 122, 4),
    ("Vad är en dator?", 122, 4),
    ("Binära tal - Introduktion", 122, 4),
    ("Binära tal - Varför?", 123, 4),
    ("Binära tal - I Datorer", 123, 4),
    ("Hexadecimala Tal", 124, 4),
    ("Central Processing Unit (CPU)", 124, 4),
    ("Minne i datorer", 124, 4),
    ("Maskinkod -- definition och egenskaper", 125, 4),
    ("Maskininstruktioner", 125, 4),
    ("Assembly-språk", 125, 4),
    ("Exempel på en assembly-instruktion", 126, 4),
    ("Instruktionsuppsättningsarkitektur (ISA)", 126, 4),
    ("Maskinkod vs. Högnivåspråk", 126, 4),
    ("Laboration -- c3pu", 127, 4),
    ("Vad är c3pu?", 127, 4),
    ("Övning programs", 128, 3),
    ("Grunduppgifter", 128, 4),
    ("Extrauppgifter; träna mer", 133, 4),
    ("Fördjupningsuppgifter; utmaningar", 135, 4),
    ("Laboration", 137, 3),
    ("Kort teori om maskinkod", 138, 4),
    ("Datorarbete", 139, 4),
    ("Extrauppgifter (frivilliga)", 142, 4),
    ("Funktioner och abstraktion", 145, 2),
    ("Teori", 146, 3),
    ("Vad är abstraktion?", 146, 4),
    ("Exempel på abstraktionsmekanismer inom datavetenskapen", 146, 4),
    ("Funktion", 146, 4),
    ("Deklarera funktioner, överlagring", 147, 4),
    ("Funktioner med defaultargument", 147, 4),
    ("Funktioner med namngivna argument", 147, 4),
    ("Enhetlig access", 148, 4),
    ("Anropsstacken och objektheapen", 148, 4),
    ("Anropsstacken och aktiveringsposter", 149, 4),
    ("Vad är en stack trace?", 149, 4),
    ("Hur läsa en stack trace?", 149, 4),
    ("Lokala funktioner", 150, 4),
    ("Funktioner är äkta värden i Scala", 150, 4),
    ("Funktionsvärden kan vara argument", 151, 4),
    ("Applicera funktioner på element i samlingar med map", 151, 4),
    ("Applicera funktioner på element i samlingar med map", 152, 4),
    ("Äkta funktioner", 152, 4),
    ("Exempel på oäkta funktioner", 152, 4),
    ("Slumptalsfrö", 153, 4),
    ("Anonyma funktioner", 153, 4),
    ("Applicera anonyma funktioner på element i samlingar", 154, 4),
    ("Platshållarsyntax för anonyma funktioner", 154, 4),
    ("Exempel på platshållarsyntax med reduceLeft", 154, 4),
    ("Predikat, med och utan namn", 155, 4),
    ("Funktionsvärde vid tom parameterlista", 155, 4),
    ("Hur fungerar egentligen upprepa i Kojo?", 156, 4),
    ("Multipla parameterlistor", 156, 4),
    ("Värdeanrop och namnanrop", 156, 4),
    ("Klammerparenteser vid ensam parameter", 157, 4),
    ("Skapa din egen kontrollstruktur", 157, 4),
    ("Kolon vid ensam parameter", 157, 4),
    ("Stegade funktioner, Curry-funktioner", 158, 4),
    ("Funktion med fångad variabelrymd", 158, 4),
    ("Rekursiva funktioner", 158, 4),
    ("Loopa med rekursion", 159, 4),
    ("Rekursiva datastrukturer", 159, 4),
    ("Kompilera om det som ändrats vid varje sparning", 160, 4),
    ("Övning functions", 161, 3),
    ("Grunduppgifter; förberedelse inför laboration", 161, 4),
    ("Extrauppgifter; träna mer", 165, 4),
    ("Fördjupningsuppgifter; utmaningar", 168, 4),
    ("Laboration", 171, 3),
    ("Krav", 171, 4),
    ("Tips för att komma igång", 171, 4),
    ("Inspiration", 172, 4),
    ("Objekt och inkapsling", 174, 2),
    ("Teori", 175, 3),
    ("Vad rymmer sköldpaddan i Kojo i sitt tillstånd?", 175, 4),
    ("Vad är ett objekt?", 175, 4),
    ("Deklarera, allokera, referera", 175, 4),
    ("Olika sätt att allokera objekt", 176, 4),
    ("Vad är ett singelobjekt?", 176, 4),
    ("Allokering", 177, 4),
    ("Punktnotation, tillståndsförändring med tilldelning", 177, 4),
    ("Punktnotation och operatornotation", 177, 4),
    ("Namnrymd och skuggning", 178, 4),
    ("Inkapsling", 178, 4),
    ("Idiom", 179, 4),
    ("Principen om enhetlig access", 179, 4),
    ("Exempel", 179, 4),
    ("Exempel", 180, 4),
    ("Tillståndsändring", 180, 4),
    ("Modul", 180, 4),
    ("Deklarera paket", 181, 4),
    ("Kompilera paket", 181, 4),
    ("Paket i REPL", 182, 4),
    ("Vad är en tupel?", 182, 4),
    ("Tupler som parametrar och returvärde.", 182, 4),
    ("Ett smidigt sätt att skapa 2-tupler med metoden ->", 183, 4),
    ("Typalias för att abstrahera typnamn", 183, 4),
    ("Lata variabler med fördröjd initialisering", 183, 4),
    ("Singelobjekt är lata", 184, 4),
    ("Vad är skillnaden mellan val, var, def, lazy val?", 184, 4),
    ("Fallgrop", 184, 4),
    ("Programmeringsparadigm", 185, 4),
    ("Funktioner är äkta objekt i Scala", 185, 4),
    ("Fördjupning", 185, 4),
    ("Vad är en klass?", 186, 4),
    ("Vad är en klass?", 186, 4),
    ("Använda klassen Color", 186, 4),
    ("Lägg till metoder i efterhand med extension", 187, 4),
    ("Kollektiva extensionsmetoder", 187, 4),
    ("Import av alla namn i en viss modul", 188, 4),
    ("Namnbyte vid import", 188, 4),
    ("Exkludera (gömma) namn vid import", 188, 4),
    ("Lokal import-deklaration", 189, 4),
    ("Export", 189, 4),
    ("Använda dokumentation för färdiga klasser.", 189, 4),
    ("Vad är en jar-fil?", 190, 4),
    ("Öppen källkod på Maven Central", 190, 4),
    ("Vad är classpath?", 190, 4),
    ("Färdiga grafikmetoder i klassen PixelWindow", 190, 4),
    ("Automatiska beroenden med Scala CLI i REPL", 191, 4),
    ("Köra program + kodbiblitek med Scala CLI", 191, 4),
    ("Kompilera om vid varje ändring", 192, 4),
    ("Övning objects", 193, 3),
    ("Grunduppgifter; förberedelse inför laboration", 193, 4),
    ("Extrauppgifter; träna mer", 200, 4),
    ("Fördjupningsuppgifter; utmaningar", 201, 4),
    ("Laboration", 204, 3),
    ("Bakgrund", 204, 4),
    ("Obligatoriska uppgifter", 204, 4),
    ("Kontrollfrågor", 209, 4),
    ("Frivilliga extrauppgifter", 209, 4),
    ("Klasser och datamodellering", 213, 2),
    ("Teori", 214, 3),
    ("En metafor för klass", 214, 4),
    ("Vad är en klass?", 214, 4),
    ("Datamodellering", 214, 4),
    ("Singelobjekt jämfört med klass", 215, 4),
    ("Förändring av objektets tillstånd", 215, 4),
    ("Bättre att initialisera med hjälp av klassparametrar", 215, 4),
    ("Klassdeklarationer och instansiering", 216, 4),
    ("Övning", 216, 4),
    ("Lösning", 217, 4),
    ("Skapa egen najs toString", 217, 4),
    ("Instansprivata klassparametrar", 218, 4),
    ("Case-klasser är som vanliga klasser med extra godis", 218, 4),
    ("Fördjupning", 219, 4),
    ("Styra användningen av infixa alfanumeriska operatorer", 219, 4),
    ("Övning", 219, 4),
    ("Exempel", 220, 4),
    ("Exempel", 220, 4),
    ("Instansiering med direkt användning av new", 221, 4),
    ("Indirekt instansiering med fabriksmetoder", 221, 4),
    ("Hur förhindra direkt instansiering?", 221, 4),
    ("Kompanjonsobjekt med indirekt instansiering", 222, 4),
    ("Användning av kompanjonsobjekt med fabriksmetoder", 222, 4),
    ("Alternativa direktinstansieringar med default-argument", 223, 4),
    ("Alternativa sätt att instansiera med fabriksmetod", 223, 4),
    ("Medlemmar som bara behövs i en enda upplaga", 223, 4),
    ("Medlemmar i singelobjekt är statiskt allokerade", 224, 4),
    ("Attribut i kompanjonsobjekt användas för sådant som är gemensamt för alla instanser", 224, 4),
    ("Övning", 225, 4),
    ("Case-klasser", 225, 4),
    ("Exempel", 225, 4),
    ("Vad är en konstruktor?", 226, 4),
    ("Fördjupning", 226, 4),
    ("Fördjupning", 226, 4),
    ("Referens saknas", 227, 4),
    ("Exempel", 227, 4),
    ("Defaultvärden under pågående konstruktion", 228, 4),
    ("Problem med initialisering av attribut vid konstruktion", 228, 4),
    ("Vilka värden har attribut medan konstruktion pågår?", 228, 4),
    ("Hur undvika initialiseringsproblem vid konstruktion?", 229, 4),
    ("Be kompilatorn att varna vid initialiseringsproblem", 229, 4),
    ("Be kompilatorn ge fler bra varningar", 230, 4),
    ("Referensen this", 230, 4),
    ("Getters och setters", 231, 4),
    ("Java-exempel", 231, 4),
    ("Motsvarande JPerson i Scala", 232, 4),
    ("Förhindra felaktiga attributvärden med setters", 232, 4),
    ("Getters och setters i Scala", 232, 4),
    ("Referenslikhet eller innehållslikhet?", 233, 4),
    ("Exempel", 233, 4),
    ("Referenslikhet och egna klasser", 234, 4),
    ("Case-klasser ger innehållslikhet", 234, 4),
    ("Likhet och case-klasser", 234, 4),
    ("Sammanfattning case-klass-godis", 234, 4),
    ("Implementation saknas", 235, 4),
    ("Exempel", 235, 4),
    ("Övning classes", 236, 3),
    ("Grunduppgifter; förberedelse inför laboration", 236, 4),
    ("Extrauppgifter; träna mer", 242, 4),
    ("Fördjupningsuppgifter; utmaningar", 246, 4),
    ("Laboration", 251, 3),
    ("Mönster och felhantering", 252, 2),
    ("Teori", 253, 3),
    ("Bastypen för alla typer", 253, 4),
    ("Alla typer är subtyper till Any", 253, 4),
    ("Dina egna referenstyper är subtyper till AnyRef", 253, 4),
    ("Vad är matchning?", 254, 4),
    ("Plocka isär ett objekt i sina beståndsdelar med mönster", 254, 4),
    ("Kolla om det passar med nästlade if-uttryck", 254, 4),
    ("Kolla om det passar med match-uttryck", 255, 4),
    ("Syntax för match-uttryck", 255, 4),
    ("Matchning med gard", 256, 4),
    ("Matchning med variabelmönster", 256, 4),
    ("Matchning med eller-mönster", 256, 4),
    ("Matchning med typade mönster", 257, 4),
    ("Fördjupning", 257, 4),
    ("Konstruktormönster med case-klasser", 258, 4),
    ("Plocka isär samlingar med djupa mönster", 258, 4),
    ("Matchning på tupler", 258, 4),
    ("Mönstermatchning och uppräkning med case-objekt", 259, 4),
    ("Mönstermatchning och förseglade typer", 259, 4),
    ("Mönstermatcha enumeration", 260, 4),
    ("Stora/små begynnelsebokstäver vid matchning", 260, 4),
    ("Stora/små begynnelsebokstäver vid matchning", 260, 4),
    ("Mönster på andra ställen än i match", 261, 4),
    ("Mönsterdelar och variabelt antal argument", 261, 4),
    ("Partiella funktioner och metoden collect", 261, 4),
    ("Fördjupning", 262, 4),
    ("Hur hantera saknade värden?", 262, 4),
    ("En gemensam bastyp för ett värde som kanske saknas", 263, 4),
    ("Option för hantering av ev. saknade värden", 263, 4),
    ("Några smidiga metoder på Option", 263, 4),
    ("Några samlingsmetoder som ger en Option, övning", 264, 4),
    ("Några samlingsmetoder som ger en Option, svar", 264, 4),
    ("Vad är ett undantag (eng. exception)?", 265, 4),
    ("Orsaka undantag indirekt med require och assert", 265, 4),
    ("Kasta undantag direkt med primitiva throw", 265, 4),
    ("En gemensam bastyp för något som kan misslyckas", 266, 4),
    ("Hantera undantag som ett värde med Try", 266, 4),
    ("Primitiva try-catch-uttryck", 267, 4),
    ("Undvik undantag om det går", 267, 4),
    ("Fördjupning", 268, 4),
    ("Fördjupning", 268, 4),
    ("Fördjupning", 268, 4),
    ("Fördjupning", 269, 4),
    ("Fördjupning", 269, 4),
    ("Övning patterns", 271, 3),
    ("Grunduppgifter; förberedelse inför laboration", 271, 4),
    ("Fördjupningsuppgifter; utmaningar", 276, 4),
    ("Laboration", 282, 3),
    ("Bakgrund", 283, 4),
    ("Obligatoriska krav", 283, 4),
    ("Valbara krav -- välj minst ett", 284, 4),
    ("Förberedelser inför redovisningen", 284, 4),
    ("Tips och förslag", 284, 4),
    ("Sekvenser och enumerationer", 287, 2),
    ("Teori", 288, 3),
    ("Vad är en sekvens?", 288, 4),
    ("Exempel", 288, 4),
    ("Iterera över element i en sekvens", 288, 4),
    ("Lägg till i början och i slutet av en sekvens", 289, 4),
    ("Egenskaper hos några sekvenssamlingar i Scala", 289, 4),
    ("Vilken sekvenssamling ska jag välja?", 290, 4),
    ("Några konstigheter med Array", 290, 4),
    ("Oföränderlig eller förändringsbar?", 291, 4),
    ("Vad är en sekvensalgoritm?", 291, 4),
    ("Använda färdiga sekvenssamlingsmetoder", 291, 4),
    ("Några användbara samlingsmetoder vid implementation av sekvensalgoritmer", 292, 4),
    ("Uppdaterad sekvens med kraftfulla metoden patch", 292, 4),
    ("Använda for-uttryck för filtrering med hjälp av gard", 292, 4),
    ("Använda samlingsmetoden filter för filtrering", 293, 4),
    ("Vanliga sekvensproblem som funktionshuvuden", 293, 4),
    ("Implementation av sekvensproblem med for-uttryck eller färdiga samlingsmetoder", 293, 4),
    ("Implementation av sekvensproblem med map, filter", 294, 4),
    ("Hierarki av samlingstyper i scala.collection v2.13", 294, 4),
    ("Lämna det öppet", 294, 4),
    ("Implementation med generiska funktioner", 295, 4),
    ("Fördjupning", 295, 4),
    ("Fördjupning", 296, 4),
    ("Repeterade parametrar blir sekvens", 296, 4),
    ("Sekvenssamling som argument till repeterade parametrar", 297, 4),
    ("Enumerationer har en ordning", 297, 4),
    ("Enumerationer kan ha parametrar och medlemmar", 297, 4),
    ("Enum kan motsvara fullfjädrade case-klasser", 298, 4),
    ("Enum och mönster-matchning", 298, 4),
    ("Fördelar med enum jämfört med uppräkning med heltal", 299, 4),
    ("Registrering", 299, 4),
    ("Registrering av tärningskast i Array", 300, 4),
    ("Registrering av tärningskast i Array", 300, 4),
    ("Skapa lösningar på sekvensproblem från grunden", 300, 4),
    ("Skapa ny sekvenssamling eller ändra på plats?", 301, 4),
    ("Algoritm", 301, 4),
    ("Implementation av SEQ-COPY med while", 301, 4),
    ("Typ-alias för att abstrahera typnamn", 302, 4),
    ("Exempel", 302, 4),
    ("Pseudo-kod för SEQ-INSERT-COPY", 303, 4),
    ("Insättning/borttagning i kopia av primitiv Array", 303, 4),
    ("Exempel", 303, 4),
    ("Implementera Polygon", 304, 4),
    ("Exempel", 304, 4),
    ("Exempel", 305, 4),
    ("Exempel", 305, 4),
    ("Att sortera och jämföra strängar lexikografiskt", 306, 4),
    ("Jämföra strängar", 306, 4),
    ("Algoritmexempel", 306, 4),
    ("Algoritmexempel", 307, 4),
    ("Jämföra strängar", 307, 4),
    ("Jämföra strängar", 307, 4),
    ("Jämföra strängar", 308, 4),
    ("Sökning", 308, 4),
    ("Linjärsökning", 309, 4),
    ("Sortering", 309, 4),
    ("Algoritmisk komplexitet", 310, 4),
    ("Det finns många olika sorteringsalgoritmer", 310, 4),
    ("Bogo sort", 310, 4),
    ("Sortera till ny vektor med insättningssortering", 310, 4),
    ("Sortera till ny vektor med insättningssortering", 311, 4),
    ("Sortera till ny samling med godtyckligt ordningspredikat", 311, 4),
    ("Insättningssortering på plats -- pseudo-kod", 312, 4),
    ("Insättningssortering på plats -- implementation", 312, 4),
    ("Övning sequences", 313, 3),
    ("Grunduppgifter; förberedelse inför laboration", 313, 4),
    ("Extrauppgifter; träna mer", 321, 4),
    ("Fördjupningsuppgifter; utmaningar", 324, 4),
    ("Laboration", 329, 3),
    ("Bakgrund", 329, 4),
    ("Given kod", 330, 4),
    ("Obligatoriska uppgifter", 330, 4),
    ("Frivilliga extrauppgifter", 334, 4),
    ("Bilder med exempel på olika pokerhänder", 334, 4),
    ("Nästlade och generiska strukturer, typsättning", 337, 2),
    ("Teori programmering", 338, 3),
    ("Veckans labb", 338, 4),
    ("Vad är en matris?", 338, 4),
    ("Indexering i en matris", 338, 4),
    ("Hur skapa matriser?", 339, 4),
    ("Hur indexera i matriser?", 339, 4),
    ("Hur indexera i matriser?", 340, 4),
    ("Uppdatering av en förändringsbar nästlad struktur", 340, 4),
    ("Uppdatering av en förändringsbar nästlad struktur", 340, 4),
    ("Några olika sätt att skapa förändringsbara matriser", 341, 4),
    ("Exempel på skapande av oföränderlig nästlad struktur", 341, 4),
    ("Exempel på skapande av oföränderlig nästlad struktur", 342, 4),
    ("Uppdatering av en oföränderlig nästlad struktur", 342, 4),
    ("Uppdatering av en oföränderlig nästlad struktur", 342, 4),
    ("Iterera över nästlad struktur", 343, 4),
    ("Iterera över nästlad struktur", 343, 4),
    ("Övningsexempel", 344, 4),
    ("Övningsexempel", 344, 4),
    ("Iterera över nästlad struktur", 344, 4),
    ("Iterera över nästlad struktur", 345, 4),
    ("Nästlade for-uttryck", 345, 4),
    ("Nästlade for-uttryck", 345, 4),
    ("Nästlade map-uttryck", 346, 4),
    ("Nästlade map-uttryck", 346, 4),
    ("Fallgrop", 346, 4),
    ("Kolla likhet mellan två heltalsmatriser (uppfinner hjulet)", 346, 4),
    ("Använd INTE sameElements på nästlade arrayer", 347, 4),
    ("Kontroll av innehållslikhet mellan nästlade arrayer", 347, 4),
    ("Exempel", 348, 4),
    ("Exempel", 348, 4),
    ("Vad är en typparameter?", 348, 4),
    ("Exempel", 349, 4),
    ("Exempel", 349, 4),
    ("Fallgrop", 350, 4),
    ("Debugging -- Appendix D", 350, 4),
    ("Den första buggen", 350, 4),
    ("Olika sorters fel?", 351, 4),
    ("När upptäcks fel?", 351, 4),
    ("Förebygga fel", 352, 4),
    ("Hitta felorsaken", 352, 4),
    ("Åtgärda fel", 352, 4),
    ("Använda en debugger", 353, 4),
    ("Teori", 354, 3),
    ("Ordbehandling", 354, 4),
    ("LaTeX - Arbetssätt och Exempel", 354, 4),
    ("Ett större exempel", 354, 4),
    ("Interaktiv Demonstration", 354, 4),
    ("LaTeX-historik", 355, 4),
    ("Arbeta med LaTeX", 355, 4),
    ("Fördelar med LaTeX", 355, 4),
    ("Dags att hoppa in i LaTeX!", 355, 4),
    ("Använda Kommandon i LaTeX", 356, 4),
    ("Exempel", 356, 4),
    ("Dokumentklasser", 356, 4),
    ("Omgivningar", 357, 4),
    ("Löpande text", 357, 4),
    ("Rubriker", 358, 4),
    ("Ändra textens utseende", 358, 4),
    ("Specialtecken", 358, 4),
    ("Fotnoter", 358, 4),
    ("Citationstecken (1/2)", 359, 4),
    ("Citationstecken (2/2)", 359, 4),
    ("Listor", 359, 4),
    ("Definitioner", 360, 4),
    ("Tabeller", 360, 4),
    ("Flytande tabeller", 360, 4),
    ("Att referera till etiketter", 361, 4),
    ("Programlistor", 361, 4),
    ("Programlistor med listings", 361, 4),
    ("Öka eller minska avstånd", 362, 4),
    ("Matematiska formler", 362, 4),
    ("Enkla formler", 362, 4),
    ("Symboler, index", 363, 4),
    ("Exponenter, rötter", 363, 4),
    ("Integraler, summor", 363, 4),
    ("Funktioner", 363, 4),
    ("Matriser, parenteser", 364, 4),
    ("Bilder", 364, 4),
    ("Bilder med figurmiljö", 364, 4),
    ("Egna kommandon", 364, 4),
    ("LaTeX på egen dator", 365, 4),
    ("Övning matrices", 366, 3),
    ("Grunduppgifter; förberedelse inför laboration", 366, 4),
    ("Extrauppgifter; träna mer", 370, 4),
    ("Fördjupningsuppgifter; utmaningar", 372, 4),
    ("Laboration", 374, 3),
    ("Bakgrund", 374, 4),
    ("Obligatoriska krav", 375, 4),
    ("Valbara krav -- välj minst ett", 376, 4),
    ("Tips och förslag", 377, 4),
    ("Laboration", 379, 3),
    ("Datorarbete", 379, 4),
    ("Rapport typsatt med LaTeX", 381, 4),
    ("Mängder och tabeller, versionshantering", 385, 2),
    ("Teori programmering", 386, 3),
    ("Hierarki av samlingstyper i scala.collection v2.13", 386, 4),
    ("Metoden iterator ger en engångs-iterator", 386, 4),
    ("Mer specifika samlingstyper i scala.collection", 386, 4),
    ("Några oföränderliga och förändringsbara sekvenssamlingar", 387, 4),
    ("Några användbara metoder på samlingar", 388, 4),
    ("Ändra på plats i förändringsbar samling", 388, 4),
    ("Repetition", 389, 4),
    ("En sträng är också en IndexedSeq[Char]", 389, 4),
    ("Konvertera mellan olika samlingstyper", 390, 4),
    ("Vad är en mängd?", 390, 4),
    ("Oföränderlig mängd", 390, 4),
    ("Mysteriet med de försvunna elementen", 391, 4),
    ("Förändringsbar mängd", 391, 4),
    ("Speciella metoder på förändringsbar mängd", 392, 4),
    ("Vad är en nyckel-värde-tabell?", 392, 4),
    ("Den fantastiska nyckel-värde-tabellen Map", 392, 4),
    ("Oföränderlig nyckel-värde-tabell", 393, 4),
    ("Fler exempel nyckel-värde-tabell", 393, 4),
    ("Från sekvens av par till tabell", 394, 4),
    ("Övning", 394, 4),
    ("Övning", 394, 4),
    ("Lösning", 395, 4),
    ("Speciella metoder på förändringsbar tabell", 395, 4),
    ("Fördjupning", 395, 4),
    ("Övning", 396, 4),
    ("Övning", 396, 4),
    ("Lösning", 396, 4),
    ("Metoden sliding", 397, 4),
    ("Metoderna zipWithIndex, groupBy", 397, 4),
    ("Fler användbara samlingsmetoder", 397, 4),
    ("Serialisering och deserialisering", 398, 4),
    ("Läsa text från fil och webbsida", 398, 4),
    ("Serialisering i modulen introprog.IO", 398, 4),
    ("Teori datorer och datoranvändning", 400, 3),
    ("Vad är versionshantering?", 400, 4),
    ("Versionshanteringssystem", 400, 4),
    ("Typer av versionshanteringssystem (1/2)", 400, 4),
    ("Centraliserad versionshantering", 401, 4),
    ("Typer av versionshanteringssystem (2/2)", 401, 4),
    ("Distrubuerad versionshantering", 402, 4),
    ("Introduktion till Git", 402, 4),
    ("Git vs. GitHub", 402, 4),
    ("Grundläggande Git-kommandon", 403, 4),
    ("Git-modellen", 403, 4),
    ("Vad är en Commit?", 404, 4),
    ("Grenar (Branches)", 404, 4),
    ("Varför grenar (branches)?", 404, 4),
    ("Vilka problem kan uppstå?", 404, 4),
    ("Exempel", 405, 4),
    ("Ett större exempel", 405, 4),
    ("Arbeta distribuerat med Git", 406, 4),
    ("Remote", 406, 4),
    ("Git Reset", 406, 4),
    ("Local vs remote", 407, 4),
    ("Local vs remote", 407, 4),
    ("Båda samtidigt!? -- push", 408, 4),
    ("Båda samtidigt!? -- fetch", 408, 4),
    ("Båda samtidigt!? -- merge efter fetch", 409, 4),
    ("Merge-situationer", 409, 4),
    ("Fast-forward merge", 410, 4),
    ("Vanlig merge -- skapar en merge commit", 411, 4),
    ("Mergekonflikt", 411, 4),
    ("Rebase", 412, 4),
    ("Bra att veta", 412, 4),
    ("Veckans laboration", 412, 4),
    ("Vad händer nu?", 413, 4),
    ("Övning lookup", 414, 3),
    ("Grunduppgifter; förberedelse inför laboration", 414, 4),
    ("Extrauppgifter; träna mer", 418, 4),
    ("Fördjupningsuppgifter; utmaningar", 419, 4),
    ("Laboration", 421, 3),
    ("Bakgrund", 421, 4),
    ("Obligatoriska uppgifter", 421, 4),
    ("Kontrollfrågor", 426, 4),
    ("Frivilliga uppgifter", 427, 4),
    ("Laboration", 429, 3),
    ("Datorarbete", 430, 4),
    ("Git-kommandon", 439, 4),
    ("Arv och komposition", 440, 2),
    ("Teori", 441, 3),
    ("Vad är arv?", 441, 4),
    ("Varför behövs arv?", 441, 4),
    ("Klassdiagram med UML (Unified Modeling Language)", 442, 4),
    ("Exempel", 442, 4),
    ("Alternativ till arv", 442, 4),
    ("Exempel på komposition i snake-labben", 443, 4),
    ("Behovet av gemensam bastyp", 443, 4),
    ("Varför syns inte gemensam medlem i en typunion?", 443, 4),
    ("Skapa en gemensam bastyp med arv", 444, 4),
    ("Skapa en gemensam bastyp med trait och extends", 444, 4),
    ("En gemensam bastyp med gemensamma delar", 445, 4),
    ("Placera gemensamma delar i bastypen", 445, 4),
    ("Scalas typhierarki", 445, 4),
    ("Implicita supertyper till dina egna klasser", 446, 4),
    ("Vad är en trait?", 446, 4),
    ("Vad används en trait till?", 447, 4),
    ("En trait kan ha abstrakta medlemmar", 447, 4),
    ("En trait kan ha parametrar", 447, 4),
    ("Abstrakta och konkreta medlemmar", 448, 4),
    ("Undvika kodduplicering med hjälp av arv", 448, 4),
    ("Varför kan kodduplicering orsaka problem?", 449, 4),
    ("Subtypspolymorfism och dynamisk bindning", 449, 4),
    ("Exempel", 450, 4),
    ("En final medlem kan ej överskuggas", 450, 4),
    ("Protected ger synlighet begränsad till subtyper", 451, 4),
    ("Filnamnsregler och -konventioner", 451, 4),
    ("Klasser, arv och klassparametrar", 452, 4),
    ("Statisk och dynamisk typ", 452, 4),
    ("Inmixning", 453, 4),
    ("Körtidstyp vid inmixning", 453, 4),
    ("Anonym klass", 454, 4),
    ("Hur förhindra subtypning?", 454, 4),
    ("Förseglade typer med sealed", 455, 4),
    ("Öppen klass signalerar uppmuntrad subtypning", 455, 4),
    ("Trait eller abstrakt klass?", 455, 4),
    ("En trait får ej vidarebefordra parametrar", 456, 4),
    ("Medlemmar, arv och överskuggning", 456, 4),
    ("Fördjupning", 457, 4),
    ("Fördjupning", 457, 4),
    ("Fördjupning", 458, 4),
    ("Att skilja på mitt och ditt med super", 458, 4),
    ("Terminologi och nyckelord vid arv", 459, 4),
    ("Vad är en algebraisk datatyp?", 459, 4),
    ("En case-klass är en produkt.", 460, 4),
    ("Algebraisk datatyp, kombinerad produkt och summa", 460, 4),
    ("Algebraisk datatyp med typparameter", 461, 4),
    ("Algebraisk datatyp med typparameter", 461, 4),
    ("Övning inheritance", 462, 3),
    ("Grunduppgifter; förberedelse inför laboration", 462, 4),
    ("Extrauppgifter; träna mer", 467, 4),
    ("Fördjupningsuppgifter; utmaningar", 468, 4),
    ("Grupplaboration", 473, 3),
    ("Bakgrund", 473, 4),
    ("Obligatoriska funktionella krav", 474, 4),
    ("Obligatoriska design-krav", 475, 4),
    ("Valbara krav -- varje person ska välja minst ett", 479, 4),
    ("Tips och förslag", 479, 4),
    ("Varians och kontextparametrar", 483, 2),
    ("Teori", 484, 3),
    ("Typparameter, generisk struktur, typkonstruktor", 484, 4),
    ("Olika sätt att begränsa generiska typer", 484, 4),
    ("Övre och undre typgräns", 485, 4),
    ("Exempel på övre och undre typgräns", 485, 4),
    ("Vad är varians?", 486, 4),
    ("Varför behövs varians?", 486, 4),
    ("Kovarians (eng. covariance)", 486, 4),
    ("Kontravarians", 487, 4),
    ("Kontravarians (eng. contravariance)", 487, 4),
    ("Variansproblem -- tack kompilatorn!", 488, 4),
    ("När använda vilken slags varians?", 488, 4),
    ("Invarians vid förändringsbarhet", 489, 4),
    ("Typjoker", 489, 4),
    ("Mer om varians för den nyfikne", 490, 4),
    ("Egentyp + anonym klass för att injektera beroenden", 490, 4),
    ("Vad är fördelen med egentyper i stället för arv?", 490, 4),
    ("Typunioner med eller-operator", 491, 4),
    ("Intersektionstyp med och-operator", 491, 4),
    ("Transparenta typer", 491, 4),
    ("Vad är ett bra api?", 492, 4),
    ("Api-desgin med Scala", 492, 4),
    ("Sammanhanget är avgörande när du kodar!", 493, 4),
    ("Repetition", 493, 4),
    ("Repetition", 494, 4),
    ("Givna värden + kontextparameter", 494, 4),
    ("Går det inte lika bra att ha en global variabel?", 494, 4),
    ("Import av kontextparameter", 495, 4),
    ("Framkalla värde med summon", 495, 4),
    ("Prioritetsordning vid framkallning av givna värden", 496, 4),
    ("Ad hoc polymorfism", 496, 4),
    ("Hur få typklassen Parser att funka för fler typer?", 497, 4),
    ("Namnet på kontextparametrar kan utelämnas", 497, 4),
    ("Kontextgräns", 497, 4),
    ("Ännu smidigare typklass med extensionsmetod", 498, 4),
    ("Sortera samlingar med given ordning", 498, 4),
    ("Sortera samlingar med ännu smidigare given ordning", 499, 4),
    ("Förslag på användning av kontextparameter i snake-labben", 499, 4),
    ("Översikt av kursens avslutning", 499, 4),
    ("Övning context", 501, 3),
    ("Grunduppgifter; förberedelse inför laboration", 501, 4),
    ("Extrauppgifter; träna mer", 502, 4),
    ("Fördjupningsuppgifter; utmaningar", 503, 4),
    ("Laboration", 508, 3),
    ("Redovisning av grupplabb", 508, 4),
    ("Fördjupning, Projekt", 509, 2),
    ("Projektuppgift", 510, 3),
    ("Om din avslutande projektuppgift", 510, 4),
    ("Projektuppgifter", 510, 4),
    ("Skapa dokumentation", 510, 4),
    ("Dokumentationskommentarer", 511, 4),
    ("Övning extra", 512, 3),
    ("Uppgifter om sökning och sortering", 512, 4),
    ("Uppgifter om trådar och jämlöpande exekvering", 519, 4),
    ("Projektuppgift", 528, 3),
    ("Fokus", 528, 4),
    ("Bakgrund", 528, 4),
    ("Krav", 528, 4),
    ("Design", 530, 4),
    ("Tips", 531, 4),
    ("Obligatoriska uppgifter", 532, 4),
    ("Frivilliga extrauppgifter", 533, 4),
    ("Exempel på historikfil", 533, 4),
    ("Exempel på körning av programmet", 533, 4),
    ("Projektuppgift", 536, 3),
    ("Bakgrund", 536, 4),
    ("Domänmodell", 536, 4),
    ("Valfria uppgifter", 543, 4),
    ("Projektuppgift", 544, 3),
    ("Bakgrund", 544, 4),
    ("Förberedelser", 544, 4),
    ("Matris med värden av typen Short", 544, 4),
    ("Användargränssnitt", 545, 4),
    ("Filter", 547, 4),
    ("Frivilliga extrauppgifter", 553, 4),
    ("Repetition", 555, 2),
    ("Repetition och tentatips", 556, 3),
    ("Repetition", 556, 4),
    ("Repetition", 556, 4),
    ("Repetition", 557, 4),
    ("Tips", 557, 4),
    ("Tips", 557, 4),
    ("Övning examprep", 559, 3),
    ("MUNTLIGT PROV", 560, 2),
    ("III Appendix", 561, 1),
    ("Kojo", 562, 2),
    ("Vad är Kojo?", 562, 3),
    ("Använda grafikbiblioteket i Kojo", 563, 3),
    ("Kojo Desktop", 564, 3),
    ("Kojo i Webbläsaren", 564, 3),
    ("Mer om Kojo", 564, 3),
    ("Terminalfönster", 567, 2),
    ("Vad är ett terminalfönster?", 567, 3),
    ("Vad är en path/sökväg?", 569, 3),
    ("Några viktiga terminalkommando", 570, 3),
    ("Editera, kompilera och exekvera", 571, 2),
    ("Vad är en editor?", 571, 3),
    ("Välj editor", 572, 4),
    ("Vad är en kompilator?", 573, 3),
    ("Java JDK", 573, 3),
    ("Scala", 574, 3),
    ("Kontrollera om du har JDK installerat", 574, 4),
    ("Installera JDK", 574, 4),
    ("Installera Scala", 575, 4),
    ("Scala Read-Evaluate-Print-Loop (REPL)", 575, 4),
    ("Kompilera och kör med Scala Command Line Interface", 576, 4),
    ("Fixa buggar", 578, 2),
    ("Vad är en bugg?", 578, 3),
    ("Olika sorters fel", 579, 4),
    ("Att förebygga fel", 582, 3),
    ("Vad är debugging?", 584, 3),
    ("Hur hittas felorsaken?", 584, 4),
    ("Åtgärda fel", 585, 3),
    ("Använda en debugger", 585, 3),
    ("Dokumentation", 587, 2),
    ("Vad gör ett dokumentationsverktyg?", 588, 3),
    ("scaladoc", 588, 3),
    ("Använda dokumentation från scaladoc", 588, 4),
    ("Skriva dokumentationskommentarer", 593, 4),
    ("Generera dokumentation", 594, 4),
    ("Byggverktyg", 595, 2),
    ("Vad gör ett byggverktyg?", 595, 3),
    ("Scala Command Line Interface scala-cli", 597, 3),
    ("Exempel på användning av Scala CLI", 597, 4),
    ("Grundläggande byggfunktioner i Scala CLI", 598, 4),
    ("Använda optioner för att styra Scala CLI", 598, 4),
    ("Generera dokumentation med Scala CLI", 599, 4),
    ("Paketering av exekverbar fil med Scala CLI", 599, 4),
    ("Optioner som användningsdirektiv i magiska kommentarer", 600, 4),
    ("Scala Build Tool sbt", 601, 3),
    ("Installera sbt", 601, 4),
    ("Använda sbt", 601, 4),
    ("Versionshantering och kodlagring", 605, 2),
    ("Vad är versionshantering?", 605, 3),
    ("Versionshanteringsverktyget Git", 605, 3),
    ("Installera git", 606, 4),
    ("Anpassa Git", 607, 4),
    ("Använda git", 607, 4),
    ("Kodlagringsplatser på nätet", 609, 3),
    ("Integrerad utvecklingsmiljö", 611, 2),
    ("Vad är en integrerad utvecklingsmiljö?", 611, 3),
    ("Visual Studio Code med tillägget Scala Metals", 612, 3),
    ("Installera VS Code och Metals", 612, 4),
    ("Köra program i VS Code", 612, 4),
    ("Använda debuggern i VS Code", 614, 4),
    ("JetBrains IntelliJ IDEA med Scala-plugin", 615, 3),
    ("Installera IntelliJ IDEA", 617, 4),
    ("Skapa webb-appar med ScalaJS", 618, 2),
    ("Introduktion till Java", 619, 2),
    ("Teori", 620, 3),
    ("Övning scalajava och labb javatext", 620, 4),
    ("Många nyheter i senare Java-versioner", 620, 4),
    ("Testa Java i jshell", 621, 4),
    ("Grundläggande likheter och skillnader Java--Scala", 621, 4),
    ("Huvudprogram i Scala och Java", 621, 4),
    ("Loopa genom argumenten i ett Java-huvudprogram", 622, 4),
    ("HIGHSCORE implementerad i Java", 622, 4),
    ("Några saker som finns i Java men inte i Scala", 623, 4),
    ("Några saker som finns i Scala men inte i Java (ännu...)", 623, 4),
    ("Begränsningar med funktionsprogrammering i Java", 624, 4),
    ("Grundtyper i Scala och primitiva typer Java", 625, 4),
    ("Javas switch-sats", 625, 4),
    ("Javas switch-sats utan break", 626, 4),
    ("Javas switch-sats med glömd break", 626, 4),
    ("Syntax för variabeldeklaration i Scala och Java", 628, 4),
    ("For-sats i Scala och Java", 628, 4),
    ("For-sats i Scala med indices", 629, 4),
    ("For-satser och arrayer i Java", 629, 4),
    ("Implementation av SEQ-COPY i Java med for-sats", 630, 4),
    ("Element för element med speciell for-each-sats i Java", 630, 4),
    ("Typisk utformning av Java-klass", 630, 4),
    ("Statiska medlemmar i Java", 631, 4),
    ("Exempel", 631, 4),
    ("Exempel", 632, 4),
    ("Exempel", 632, 4),
    ("Exempel", 633, 4),
    ("Exempel", 633, 4),
    ("Exempel", 634, 4),
    ("Scalas case-klass-godis finns inte i Java", 636, 4),
    ("Repetition", 636, 4),
    ("Syntax för Array i Scala och Java", 637, 4),
    ("Exempel", 637, 4),
    ("Polygon med primitiv array i Java", 637, 4),
    ("Polygon med primitiv array i Java", 638, 4),
    ("Scanna filer och strängar med java.util.Scanner", 638, 4),
    ("Exempel", 639, 4),
    ("Använda Java-samlingar i Scala med CollectionConverters", 639, 4),
    ("Generiska samlingar i Java", 639, 4),
    ("Om ArrayList i Java", 640, 4),
    ("Polygon med ArrayList i Java", 640, 4),
    ("Några viktiga operationer på ArrayList<E>", 640, 4),
    ("Övning ArrayList", 641, 4),
    ("For-each-sats i Java", 641, 4),
    ("Polygon med ArrayList", 642, 4),
    ("Polygon med ArrayList", 642, 4),
    ("Polygon med ArrayList", 642, 4),
    ("Övning ArrayList", 643, 4),
    ("Lösning ArrayList", 643, 4),
    ("For-each-sats med array", 643, 4),
    ("Generiska klasser (t.ex. ArrayList) med primitiva typer", 644, 4),
    ("Wrapper-klassen Integer", 644, 4),
    ("Wrapper-klasser i java.lang", 645, 4),
    ("Övning", 645, 4),
    ("Exempel", 645, 4),
    ("Specialregler för wrapper-klasser", 646, 4),
    ("Exempel", 646, 4),
    ("Fallgropar vid autoboxning", 646, 4),
    ("Referenslikhet eller innehållslikhet i Scala och Java", 647, 4),
    ("Fallgrop med samlingar", 647, 4),
    ("Fullständigt recept för equals", 648, 4),
    ("Villkorsuttryck i Java", 648, 4),
    ("Typtest och typkonvertering", 648, 4),
    ("Regler för överskuggning i Java", 648, 4),
    ("Fånga undantag i Scala och Java", 648, 4),
    ("Gränssnittet List i Java", 649, 4),
    ("Det går inte att skapa generisk Array i Java", 649, 4),
    ("Jämföra strängar i Java", 650, 4),
    ("Jämföra strängar i Java", 650, 4),
    ("Övning java", 652, 3),
    ("Grunduppgifter; förberedelse inför laboration", 652, 4),
    ("Laboration", 672, 3),
    ("Krav", 672, 4),
    ("Frivilliga extrauppgifter", 673, 4),
    ("Inspiration och tips", 673, 4),
    ("Virtuell maskin", 674, 2),
    ("Vad är en virtuell maskin?", 674, 3),
    ("Vad innehåller kursens vm?", 675, 3),
    ("Installera kursens vm", 675, 3),
    ("IV Lösningar", 677, 1),
    ("Lösningar till övningarna", 678, 2),
    ("Lösning expressions", 679, 3),
    ("Grunduppgifter; förberedelse inför laboration", 680, 4),
    ("Extrauppgifter; träna mer", 686, 4),
    ("Fördjupningsuppgifter; utmaningar", 690, 4),
    ("Lösning programs", 694, 3),
    ("Grunduppgifter", 694, 4),
    ("Extrauppgifter; träna mer", 699, 4),
    ("Fördjupningsuppgifter; utmaningar", 701, 4),
    ("Lösning functions", 703, 3),
    ("Extrauppgifter; träna mer", 706, 4),
    ("Fördjupningsuppgifter; utmaningar", 708, 4),
    ("Lösning objects", 711, 3),
    ("Grunduppgifter; förberedelse inför laboration", 711, 4),
    ("Extrauppgifter; träna mer", 718, 4),
    ("Fördjupningsuppgifter; utmaningar", 719, 4),
    ("Lösning classes", 722, 3),
    ("Grunduppgifter; förberedelse inför laboration", 722, 4),
    ("Extrauppgifter; träna mer", 725, 4),
    ("Fördjupningsuppgifter; utmaningar", 728, 4),
    ("Lösning patterns", 734, 3),
    ("Grunduppgifter; förberedelse inför laboration", 734, 4),
    ("Fördjupningsuppgifter; utmaningar", 740, 4),
    ("Lösning sequences", 744, 3),
    ("Grunduppgifter; förberedelse inför laboration", 744, 4),
    ("Extrauppgifter; träna mer", 752, 4),
    ("Fördjupningsuppgifter; utmaningar", 755, 4),
    ("Lösning matrices", 758, 3),
    ("Grunduppgifter; förberedelse inför laboration", 758, 4),
    ("Extrauppgifter; träna mer", 761, 4),
    ("Fördjupningsuppgifter; utmaningar", 763, 4),
    ("Lösning lookup", 765, 3),
    ("Grunduppgifter; förberedelse inför laboration", 765, 4),
    ("Extrauppgifter; träna mer", 768, 4),
    ("Fördjupningsuppgifter; utmaningar", 769, 4),
    ("Lösning inheritance", 770, 3),
    ("Grunduppgifter; förberedelse inför laboration", 770, 4),
    ("Extrauppgifter; träna mer", 775, 4),
    ("Fördjupningsuppgifter; utmaningar", 776, 4),
    ("Lösning context", 779, 3),
    ("Grunduppgifter; förberedelse inför laboration", 779, 4),
    ("Extrauppgifter; träna mer", 782, 4),
    ("Fördjupningsuppgifter; utmaningar", 782, 4),
    ("Lösning extra", 788, 3),
    ("Uppgifter om sökning och sortering", 788, 4),
    ("Uppgifter om trådar och jämlöpande exekvering", 793, 4),
    ("Extrauppgifter; träna mer", 794, 4),
    ("Lösning examprep", 798, 3),
    ("Lösning java", 799, 3),
    ("Grunduppgifter; förberedelse inför laboration", 799, 4),
    
  )
